/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AttributeValueWhereUniqueInput } from "../../attributeValue/base/AttributeValueWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput } from "./BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput";
import { BillOfMaterialCreateNestedManyWithoutProductVariantsInput } from "./BillOfMaterialCreateNestedManyWithoutProductVariantsInput";
import { ProductBarcodeCreateNestedManyWithoutProductVariantsInput } from "./ProductBarcodeCreateNestedManyWithoutProductVariantsInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

@InputType()
class ProductVariantCreateInput {
  @ApiProperty({
    required: true,
    type: () => AttributeValueWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AttributeValueWhereUniqueInput)
  @Field(() => AttributeValueWhereUniqueInput)
  attributeValueId!: AttributeValueWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput,
  })
  @ValidateNested()
  @Type(() => BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput)
  @IsOptional()
  @Field(
    () => BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput,
    {
      nullable: true,
    }
  )
  billOfMaterialDetails?: BillOfMaterialDetailCreateNestedManyWithoutProductVariantsInput;

  @ApiProperty({
    required: false,
    type: () => BillOfMaterialCreateNestedManyWithoutProductVariantsInput,
  })
  @ValidateNested()
  @Type(() => BillOfMaterialCreateNestedManyWithoutProductVariantsInput)
  @IsOptional()
  @Field(() => BillOfMaterialCreateNestedManyWithoutProductVariantsInput, {
    nullable: true,
  })
  billOfMaterials?: BillOfMaterialCreateNestedManyWithoutProductVariantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductBarcodeCreateNestedManyWithoutProductVariantsInput,
  })
  @ValidateNested()
  @Type(() => ProductBarcodeCreateNestedManyWithoutProductVariantsInput)
  @IsOptional()
  @Field(() => ProductBarcodeCreateNestedManyWithoutProductVariantsInput, {
    nullable: true,
  })
  productBarcodes?: ProductBarcodeCreateNestedManyWithoutProductVariantsInput;

  @ApiProperty({
    required: true,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @Field(() => ProductWhereUniqueInput)
  productId!: ProductWhereUniqueInput;
}

export { ProductVariantCreateInput as ProductVariantCreateInput };
