import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { Decimal } from "decimal.js";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { PurchaseDetailCreateNestedManyWithoutPurchasesInput } from "./PurchaseDetailCreateNestedManyWithoutPurchasesInput";
import { PurchasePriceTypeWhereUniqueInput } from "../purchasePriceType/PurchasePriceTypeWhereUniqueInput";
import { PurchaseReturnCreateNestedManyWithoutPurchasesInput } from "./PurchaseReturnCreateNestedManyWithoutPurchasesInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type PurchaseCreateInput = {
  cashRepositoryId: CashRepositoryWhereUniqueInput;
  discountTotal: Decimal;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput | null;
  isActive?: boolean | null;
  isCancelled: boolean;
  isReplicated: boolean;
  netTotal: Decimal;
  nonTaxableTotal?: Decimal | null;
  note?: string | null;
  paid: Decimal;
  paymentTypeId: PaymentTypeWhereUniqueInput;
  purchaseDate: Date;
  purchaseDetails?: PurchaseDetailCreateNestedManyWithoutPurchasesInput;
  purchasePriceTypeId: PurchasePriceTypeWhereUniqueInput;
  purchaseReturns?: PurchaseReturnCreateNestedManyWithoutPurchasesInput;
  purchaseTotal: Decimal;
  referenceNumber?: string | null;
  remaining: Decimal;
  sequenceNumber: string;
  storeId: StoreWhereUniqueInput;
  supplierId: SupplierWhereUniqueInput;
  tax?: Decimal | null;
  taxRate?: Decimal | null;
  taxableTotal?: Decimal | null;
  tenantId?: TenantWhereUniqueInput | null;
};
