import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringFilter } from "../../util/StringFilter";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { PurchaseDetailListRelationFilter } from "../purchaseDetail/PurchaseDetailListRelationFilter";
import { PurchasePriceTypeWhereUniqueInput } from "../purchasePriceType/PurchasePriceTypeWhereUniqueInput";
import { PurchaseReturnListRelationFilter } from "../purchaseReturn/PurchaseReturnListRelationFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type PurchaseWhereInput = {
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  discountTotal?: DecimalFilter;
  id?: StringFilter;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput;
  isActive?: BooleanNullableFilter;
  isCancelled?: BooleanFilter;
  isReplicated?: BooleanFilter;
  netTotal?: DecimalFilter;
  nonTaxableTotal?: DecimalNullableFilter;
  note?: StringNullableFilter;
  paid?: DecimalFilter;
  paymentTypeId?: PaymentTypeWhereUniqueInput;
  purchaseDate?: DateTimeFilter;
  purchaseDetails?: PurchaseDetailListRelationFilter;
  purchasePriceTypeId?: PurchasePriceTypeWhereUniqueInput;
  purchaseReturns?: PurchaseReturnListRelationFilter;
  purchaseTotal?: DecimalFilter;
  referenceNumber?: StringNullableFilter;
  remaining?: DecimalFilter;
  sequenceNumber?: StringFilter;
  storeId?: StoreWhereUniqueInput;
  supplierId?: SupplierWhereUniqueInput;
  tax?: DecimalNullableFilter;
  taxRate?: DecimalNullableFilter;
  taxableTotal?: DecimalNullableFilter;
  tenantId?: TenantWhereUniqueInput;
};
