import { CashRepository } from "../cashRepository/CashRepository";
import { Decimal } from "decimal.js";
import { InvoiceType } from "../invoiceType/InvoiceType";
import { PaymentType } from "../paymentType/PaymentType";
import { PurchaseDetail } from "../purchaseDetail/PurchaseDetail";
import { PurchasePriceType } from "../purchasePriceType/PurchasePriceType";
import { PurchaseReturn } from "../purchaseReturn/PurchaseReturn";
import { Store } from "../store/Store";
import { Supplier } from "../supplier/Supplier";
import { Tenant } from "../tenant/Tenant";

export type Purchase = {
  cashRepositoryId?: CashRepository;
  createdAt: Date;
  discountTotal: Decimal;
  id: string;
  invoiceTypeId?: InvoiceType | null;
  isActive: boolean | null;
  isCancelled: boolean;
  isReplicated: boolean;
  netTotal: Decimal;
  nonTaxableTotal: Decimal | null;
  note: string | null;
  paid: Decimal;
  paymentTypeId?: PaymentType;
  purchaseDate: Date;
  purchaseDetails?: Array<PurchaseDetail>;
  purchasePriceTypeId?: PurchasePriceType;
  purchaseReturns?: Array<PurchaseReturn>;
  purchaseTotal: Decimal;
  referenceNumber: string | null;
  remaining: Decimal;
  sequenceNumber: string;
  storeId?: Store;
  supplierId?: Supplier;
  tax: Decimal | null;
  taxRate: Decimal | null;
  taxableTotal: Decimal | null;
  tenantId?: Tenant | null;
  updatedAt: Date;
};
