import { ProductionOrderCreateNestedManyWithoutStoresInput } from "./ProductionOrderCreateNestedManyWithoutStoresInput";
import { ProductCreateNestedManyWithoutStoresInput } from "./ProductCreateNestedManyWithoutStoresInput";
import { PurchaseReturnCreateNestedManyWithoutStoresInput } from "./PurchaseReturnCreateNestedManyWithoutStoresInput";
import { PurchaseCreateNestedManyWithoutStoresInput } from "./PurchaseCreateNestedManyWithoutStoresInput";
import { SaleOrderCreateNestedManyWithoutStoresInput } from "./SaleOrderCreateNestedManyWithoutStoresInput";
import { SaleReturnCreateNestedManyWithoutStoresInput } from "./SaleReturnCreateNestedManyWithoutStoresInput";
import { SaleCreateNestedManyWithoutStoresInput } from "./SaleCreateNestedManyWithoutStoresInput";
import { StoreLocationCreateNestedManyWithoutStoresInput } from "./StoreLocationCreateNestedManyWithoutStoresInput";
import { StoreTypeWhereUniqueInput } from "../storeType/StoreTypeWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type StoreCreateInput = {
  addressLine1?: string | null;
  allowSale: boolean;
  cellPhoneNumber?: string | null;
  code?: string | null;
  fax?: string | null;
  homePhoneNumber?: string | null;
  isActive: boolean;
  name: string;
  normalizedName: string;
  note?: string | null;
  productionOrders?: ProductionOrderCreateNestedManyWithoutStoresInput;
  products?: ProductCreateNestedManyWithoutStoresInput;
  purchaseReturns?: PurchaseReturnCreateNestedManyWithoutStoresInput;
  purchases?: PurchaseCreateNestedManyWithoutStoresInput;
  saleOrders?: SaleOrderCreateNestedManyWithoutStoresInput;
  saleReturns?: SaleReturnCreateNestedManyWithoutStoresInput;
  sales?: SaleCreateNestedManyWithoutStoresInput;
  storeLocations?: StoreLocationCreateNestedManyWithoutStoresInput;
  storeTypId?: StoreTypeWhereUniqueInput | null;
  street?: string | null;
  tenantId?: TenantWhereUniqueInput | null;
};
