/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { EmployeeSalaryUpdateManyWithoutFiscalMonthsInput } from "./EmployeeSalaryUpdateManyWithoutFiscalMonthsInput";
import { Type } from "class-transformer";
import { FiscalWeekUpdateManyWithoutFiscalMonthsInput } from "./FiscalWeekUpdateManyWithoutFiscalMonthsInput";
import { FiscalYearWhereUniqueInput } from "../../fiscalYear/base/FiscalYearWhereUniqueInput";

@InputType()
class FiscalMonthUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(100)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeSalaryUpdateManyWithoutFiscalMonthsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeSalaryUpdateManyWithoutFiscalMonthsInput)
  @IsOptional()
  @Field(() => EmployeeSalaryUpdateManyWithoutFiscalMonthsInput, {
    nullable: true,
  })
  employeeSalaries?: EmployeeSalaryUpdateManyWithoutFiscalMonthsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endsOn?: Date | null;

  @ApiProperty({
    required: false,
    type: () => FiscalWeekUpdateManyWithoutFiscalMonthsInput,
  })
  @ValidateNested()
  @Type(() => FiscalWeekUpdateManyWithoutFiscalMonthsInput)
  @IsOptional()
  @Field(() => FiscalWeekUpdateManyWithoutFiscalMonthsInput, {
    nullable: true,
  })
  fiscalWeeks?: FiscalWeekUpdateManyWithoutFiscalMonthsInput;

  @ApiProperty({
    required: false,
    type: () => FiscalYearWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FiscalYearWhereUniqueInput)
  @IsOptional()
  @Field(() => FiscalYearWhereUniqueInput, {
    nullable: true,
  })
  fiscalYear?: FiscalYearWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(300)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  mormalizedName?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(300)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startsFrom?: Date | null;
}

export { FiscalMonthUpdateInput as FiscalMonthUpdateInput };
