import { AttendanceListRelationFilter } from "../attendance/AttendanceListRelationFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { BonusRequestListRelationFilter } from "../bonusRequest/BonusRequestListRelationFilter";
import { CheckInOutListRelationFilter } from "../checkInOut/CheckInOutListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DailyMovementRequestListRelationFilter } from "../dailyMovementRequest/DailyMovementRequestListRelationFilter";
import { DayOffRequestListRelationFilter } from "../dayOffRequest/DayOffRequestListRelationFilter";
import { EmployeeDepartmentWhereUniqueInput } from "../employeeDepartment/EmployeeDepartmentWhereUniqueInput";
import { EmployeeGroupWhereUniqueInput } from "../employeeGroup/EmployeeGroupWhereUniqueInput";
import { EmployeeRoleWhereUniqueInput } from "../employeeRole/EmployeeRoleWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { JobTitleWhereUniqueInput } from "../jobTitle/JobTitleWhereUniqueInput";
import { LeaveRequestListRelationFilter } from "../leaveRequest/LeaveRequestListRelationFilter";
import { OverNightRequestListRelationFilter } from "../overNightRequest/OverNightRequestListRelationFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type EmployeeWhereInput = {
  attendances?: AttendanceListRelationFilter;
  balance?: DecimalNullableFilter;
  bonusRequests?: BonusRequestListRelationFilter;
  checkInOuts?: CheckInOutListRelationFilter;
  code?: StringNullableFilter;
  dailyMovementRequests?: DailyMovementRequestListRelationFilter;
  dayOffRequests?: DayOffRequestListRelationFilter;
  employeeDepartmentId?: EmployeeDepartmentWhereUniqueInput;
  employeeGroup?: EmployeeGroupWhereUniqueInput;
  employeeRoleId?: EmployeeRoleWhereUniqueInput;
  hireDate?: DateTimeNullableFilter;
  id?: StringFilter;
  isActive?: BooleanFilter;
  jobTitle?: JobTitleWhereUniqueInput;
  lastYearBalance?: DecimalNullableFilter;
  leavingPermissionRequests?: LeaveRequestListRelationFilter;
  name?: StringFilter;
  note?: StringNullableFilter;
  overNightRequests?: OverNightRequestListRelationFilter;
  remainingBalance?: DecimalNullableFilter;
  tenantId?: TenantWhereUniqueInput;
  usedBalance?: DecimalNullableFilter;
};
