/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PaymentVoucher } from "./PaymentVoucher";
import { PaymentVoucherCountArgs } from "./PaymentVoucherCountArgs";
import { PaymentVoucherFindManyArgs } from "./PaymentVoucherFindManyArgs";
import { PaymentVoucherFindUniqueArgs } from "./PaymentVoucherFindUniqueArgs";
import { CreatePaymentVoucherArgs } from "./CreatePaymentVoucherArgs";
import { UpdatePaymentVoucherArgs } from "./UpdatePaymentVoucherArgs";
import { DeletePaymentVoucherArgs } from "./DeletePaymentVoucherArgs";
import { PaymentVoucherService } from "../paymentVoucher.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PaymentVoucher)
export class PaymentVoucherResolverBase {
  constructor(
    protected readonly service: PaymentVoucherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "read",
    possession: "any",
  })
  async _paymentVouchersMeta(
    @graphql.Args() args: PaymentVoucherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PaymentVoucher])
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "read",
    possession: "any",
  })
  async paymentVouchers(
    @graphql.Args() args: PaymentVoucherFindManyArgs
  ): Promise<PaymentVoucher[]> {
    return this.service.paymentVouchers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PaymentVoucher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "read",
    possession: "own",
  })
  async paymentVoucher(
    @graphql.Args() args: PaymentVoucherFindUniqueArgs
  ): Promise<PaymentVoucher | null> {
    const result = await this.service.paymentVoucher(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentVoucher)
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "create",
    possession: "any",
  })
  async createPaymentVoucher(
    @graphql.Args() args: CreatePaymentVoucherArgs
  ): Promise<PaymentVoucher> {
    return await this.service.createPaymentVoucher({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentVoucher)
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "update",
    possession: "any",
  })
  async updatePaymentVoucher(
    @graphql.Args() args: UpdatePaymentVoucherArgs
  ): Promise<PaymentVoucher | null> {
    try {
      return await this.service.updatePaymentVoucher({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaymentVoucher)
  @nestAccessControl.UseRoles({
    resource: "PaymentVoucher",
    action: "delete",
    possession: "any",
  })
  async deletePaymentVoucher(
    @graphql.Args() args: DeletePaymentVoucherArgs
  ): Promise<PaymentVoucher | null> {
    try {
      return await this.service.deletePaymentVoucher(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
