import { AccountUpdateManyWithoutTenantsInput } from "./AccountUpdateManyWithoutTenantsInput";
import { ApplicationDependencyUpdateManyWithoutTenantsInput } from "./ApplicationDependencyUpdateManyWithoutTenantsInput";
import { ApplicationUpdateManyWithoutTenantsInput } from "./ApplicationUpdateManyWithoutTenantsInput";
import { AttributeValueUpdateManyWithoutTenantsInput } from "./AttributeValueUpdateManyWithoutTenantsInput";
import { AttributeUpdateManyWithoutTenantsInput } from "./AttributeUpdateManyWithoutTenantsInput";
import { BankBranchUpdateManyWithoutTenantsInput } from "./BankBranchUpdateManyWithoutTenantsInput";
import { BankTypeUpdateManyWithoutTenantsInput } from "./BankTypeUpdateManyWithoutTenantsInput";
import { BarcodeTypeUpdateManyWithoutTenantsInput } from "./BarcodeTypeUpdateManyWithoutTenantsInput";
import { BillOfMaterialDetailUpdateManyWithoutTenantsInput } from "./BillOfMaterialDetailUpdateManyWithoutTenantsInput";
import { BillOfMaterialTypeUpdateManyWithoutTenantsInput } from "./BillOfMaterialTypeUpdateManyWithoutTenantsInput";
import { BillOfMaterialUpdateManyWithoutTenantsInput } from "./BillOfMaterialUpdateManyWithoutTenantsInput";
import { CashRepositoryUpdateManyWithoutTenantsInput } from "./CashRepositoryUpdateManyWithoutTenantsInput";
import { CurrencyUpdateManyWithoutTenantsInput } from "./CurrencyUpdateManyWithoutTenantsInput";
import { CustomerUpdateManyWithoutTenantsInput } from "./CustomerUpdateManyWithoutTenantsInput";
import { EmployeeClassUpdateManyWithoutTenantsInput } from "./EmployeeClassUpdateManyWithoutTenantsInput";
import { EmployeeDepartmentUpdateManyWithoutTenantsInput } from "./EmployeeDepartmentUpdateManyWithoutTenantsInput";
import { EmployeeUpdateManyWithoutTenantsInput } from "./EmployeeUpdateManyWithoutTenantsInput";
import { ExpenseItemUpdateManyWithoutTenantsInput } from "./ExpenseItemUpdateManyWithoutTenantsInput";
import { InstallmentSaleFeeUpdateManyWithoutTenantsInput } from "./InstallmentSaleFeeUpdateManyWithoutTenantsInput";
import { InvoiceTypeUpdateManyWithoutTenantsInput } from "./InvoiceTypeUpdateManyWithoutTenantsInput";
import { OrderStatusUpdateManyWithoutTenantsInput } from "./OrderStatusUpdateManyWithoutTenantsInput";
import { PaymentMethodUpdateManyWithoutTenantsInput } from "./PaymentMethodUpdateManyWithoutTenantsInput";
import { PaymentStatusUpdateManyWithoutTenantsInput } from "./PaymentStatusUpdateManyWithoutTenantsInput";
import { PaymentTermUpdateManyWithoutTenantsInput } from "./PaymentTermUpdateManyWithoutTenantsInput";
import { PaymentTypeUpdateManyWithoutTenantsInput } from "./PaymentTypeUpdateManyWithoutTenantsInput";
import { PaymentVoucherUpdateManyWithoutTenantsInput } from "./PaymentVoucherUpdateManyWithoutTenantsInput";
import { PeriodUpdateManyWithoutTenantsInput } from "./PeriodUpdateManyWithoutTenantsInput";
import { PrintTemplateContentUpdateManyWithoutTenantsInput } from "./PrintTemplateContentUpdateManyWithoutTenantsInput";
import { PrintTemplateGroupUpdateManyWithoutTenantsInput } from "./PrintTemplateGroupUpdateManyWithoutTenantsInput";
import { PrintTemplateUpdateManyWithoutTenantsInput } from "./PrintTemplateUpdateManyWithoutTenantsInput";
import { ProductBarcodeUpdateManyWithoutTenantsInput } from "./ProductBarcodeUpdateManyWithoutTenantsInput";
import { ProductCategoryUpdateManyWithoutTenantsInput } from "./ProductCategoryUpdateManyWithoutTenantsInput";
import { ProductDepartmentUpdateManyWithoutTenantsInput } from "./ProductDepartmentUpdateManyWithoutTenantsInput";
import { ProductGroupUpdateManyWithoutTenantsInput } from "./ProductGroupUpdateManyWithoutTenantsInput";
import { ProductTypeUpdateManyWithoutTenantsInput } from "./ProductTypeUpdateManyWithoutTenantsInput";
import { ProductUnitUpdateManyWithoutTenantsInput } from "./ProductUnitUpdateManyWithoutTenantsInput";
import { ProductVariantUpdateManyWithoutTenantsInput } from "./ProductVariantUpdateManyWithoutTenantsInput";
import { ProductionAvailabilityUpdateManyWithoutTenantsInput } from "./ProductionAvailabilityUpdateManyWithoutTenantsInput";
import { ProductionDocumentUpdateManyWithoutTenantsInput } from "./ProductionDocumentUpdateManyWithoutTenantsInput";
import { ProductionOrderUpdateManyWithoutTenantsInput } from "./ProductionOrderUpdateManyWithoutTenantsInput";
import { ProductUpdateManyWithoutTenantsInput } from "./ProductUpdateManyWithoutTenantsInput";
import { PurchaseDetailUpdateManyWithoutTenantsInput } from "./PurchaseDetailUpdateManyWithoutTenantsInput";
import { PurchasePriceTypeUpdateManyWithoutTenantsInput } from "./PurchasePriceTypeUpdateManyWithoutTenantsInput";
import { PurchaseReturnDetailUpdateManyWithoutTenantsInput } from "./PurchaseReturnDetailUpdateManyWithoutTenantsInput";
import { PurchaseReturnUpdateManyWithoutTenantsInput } from "./PurchaseReturnUpdateManyWithoutTenantsInput";
import { PurchaseUpdateManyWithoutTenantsInput } from "./PurchaseUpdateManyWithoutTenantsInput";
import { ReceiptVoucherUpdateManyWithoutTenantsInput } from "./ReceiptVoucherUpdateManyWithoutTenantsInput";
import { ResourceTypeUpdateManyWithoutTenantsInput } from "./ResourceTypeUpdateManyWithoutTenantsInput";
import { ResourceUpdateManyWithoutTenantsInput } from "./ResourceUpdateManyWithoutTenantsInput";
import { RoleGroupUpdateManyWithoutTenantsInput } from "./RoleGroupUpdateManyWithoutTenantsInput";
import { SalaryItemGroupUpdateManyWithoutTenantsInput } from "./SalaryItemGroupUpdateManyWithoutTenantsInput";
import { SalaryItemTypeUpdateManyWithoutTenantsInput } from "./SalaryItemTypeUpdateManyWithoutTenantsInput";
import { SalaryItemUpdateManyWithoutTenantsInput } from "./SalaryItemUpdateManyWithoutTenantsInput";
import { SalaryLawUpdateManyWithoutTenantsInput } from "./SalaryLawUpdateManyWithoutTenantsInput";
import { SaleDetailUpdateManyWithoutTenantsInput } from "./SaleDetailUpdateManyWithoutTenantsInput";
import { SaleOrderDetailUpdateManyWithoutTenantsInput } from "./SaleOrderDetailUpdateManyWithoutTenantsInput";
import { SaleOrderUpdateManyWithoutTenantsInput } from "./SaleOrderUpdateManyWithoutTenantsInput";
import { SalePaymentUpdateManyWithoutTenantsInput } from "./SalePaymentUpdateManyWithoutTenantsInput";
import { SalePersonUpdateManyWithoutTenantsInput } from "./SalePersonUpdateManyWithoutTenantsInput";
import { SalePriceTypeUpdateManyWithoutTenantsInput } from "./SalePriceTypeUpdateManyWithoutTenantsInput";
import { SaleQuotationDetailUpdateManyWithoutTenantsInput } from "./SaleQuotationDetailUpdateManyWithoutTenantsInput";
import { SaleQuotationUpdateManyWithoutTenantsInput } from "./SaleQuotationUpdateManyWithoutTenantsInput";
import { SaleReturnDetailUpdateManyWithoutTenantsInput } from "./SaleReturnDetailUpdateManyWithoutTenantsInput";
import { SaleReturnUpdateManyWithoutTenantsInput } from "./SaleReturnUpdateManyWithoutTenantsInput";
import { SaleTaxUpdateManyWithoutTenantsInput } from "./SaleTaxUpdateManyWithoutTenantsInput";
import { SaleTeamUpdateManyWithoutTenantsInput } from "./SaleTeamUpdateManyWithoutTenantsInput";
import { SaleUpdateManyWithoutTenantsInput } from "./SaleUpdateManyWithoutTenantsInput";
import { ScrapReasonUpdateManyWithoutTenantsInput } from "./ScrapReasonUpdateManyWithoutTenantsInput";
import { SettingGroupUpdateManyWithoutTenantsInput } from "./SettingGroupUpdateManyWithoutTenantsInput";
import { SettingUpdateManyWithoutTenantsInput } from "./SettingUpdateManyWithoutTenantsInput";
import { ShiftUpdateManyWithoutTenantsInput } from "./ShiftUpdateManyWithoutTenantsInput";
import { ShippingStatusUpdateManyWithoutTenantsInput } from "./ShippingStatusUpdateManyWithoutTenantsInput";
import { StoreLocationUpdateManyWithoutTenantsInput } from "./StoreLocationUpdateManyWithoutTenantsInput";
import { StoreTypeUpdateManyWithoutTenantsInput } from "./StoreTypeUpdateManyWithoutTenantsInput";
import { StoreUpdateManyWithoutTenantsInput } from "./StoreUpdateManyWithoutTenantsInput";
import { SupplierUpdateManyWithoutTenantsInput } from "./SupplierUpdateManyWithoutTenantsInput";
import { TimeModeUpdateManyWithoutTenantsInput } from "./TimeModeUpdateManyWithoutTenantsInput";
import { TimeoffTypeUpdateManyWithoutTenantsInput } from "./TimeoffTypeUpdateManyWithoutTenantsInput";
import { UnitUpdateManyWithoutTenantsInput } from "./UnitUpdateManyWithoutTenantsInput";
import { UserUpdateManyWithoutTenantsInput } from "./UserUpdateManyWithoutTenantsInput";
import { VoucherTypeUpdateManyWithoutTenantsInput } from "./VoucherTypeUpdateManyWithoutTenantsInput";
import { WorkCenterRoutingUpdateManyWithoutTenantsInput } from "./WorkCenterRoutingUpdateManyWithoutTenantsInput";
import { WorkCenterUpdateManyWithoutTenantsInput } from "./WorkCenterUpdateManyWithoutTenantsInput";

export type TenantUpdateInput = {
  accounts?: AccountUpdateManyWithoutTenantsInput;
  applicationDependencies?: ApplicationDependencyUpdateManyWithoutTenantsInput;
  applications?: ApplicationUpdateManyWithoutTenantsInput;
  attributeValues?: AttributeValueUpdateManyWithoutTenantsInput;
  attributes?: AttributeUpdateManyWithoutTenantsInput;
  bankBranches?: BankBranchUpdateManyWithoutTenantsInput;
  bankTypes?: BankTypeUpdateManyWithoutTenantsInput;
  barcodeTypes?: BarcodeTypeUpdateManyWithoutTenantsInput;
  billOfMaterialDetails?: BillOfMaterialDetailUpdateManyWithoutTenantsInput;
  billOfMaterialTypes?: BillOfMaterialTypeUpdateManyWithoutTenantsInput;
  billOfMaterials?: BillOfMaterialUpdateManyWithoutTenantsInput;
  cashRepositories?: CashRepositoryUpdateManyWithoutTenantsInput;
  code?: string | null;
  creatorUserId?: string | null;
  currencies?: CurrencyUpdateManyWithoutTenantsInput;
  customers?: CustomerUpdateManyWithoutTenantsInput;
  description?: string | null;
  email?: string | null;
  employeeClasses?: EmployeeClassUpdateManyWithoutTenantsInput;
  employeeDepartments?: EmployeeDepartmentUpdateManyWithoutTenantsInput;
  employees?: EmployeeUpdateManyWithoutTenantsInput;
  expenseItems?: ExpenseItemUpdateManyWithoutTenantsInput;
  installmentSaleFees?: InstallmentSaleFeeUpdateManyWithoutTenantsInput;
  invoiceTypes?: InvoiceTypeUpdateManyWithoutTenantsInput;
  isActive?: boolean;
  lastModifierUserIdl?: string | null;
  name?: string;
  normalizedName?: string;
  note?: string | null;
  orderStatuses?: OrderStatusUpdateManyWithoutTenantsInput;
  paymentMethods?: PaymentMethodUpdateManyWithoutTenantsInput;
  paymentStatuses?: PaymentStatusUpdateManyWithoutTenantsInput;
  paymentTerms?: PaymentTermUpdateManyWithoutTenantsInput;
  paymentTypes?: PaymentTypeUpdateManyWithoutTenantsInput;
  paymentVouchers?: PaymentVoucherUpdateManyWithoutTenantsInput;
  periods?: PeriodUpdateManyWithoutTenantsInput;
  printTemplateContents?: PrintTemplateContentUpdateManyWithoutTenantsInput;
  printTemplateGroups?: PrintTemplateGroupUpdateManyWithoutTenantsInput;
  printTemplates?: PrintTemplateUpdateManyWithoutTenantsInput;
  productBarcodes?: ProductBarcodeUpdateManyWithoutTenantsInput;
  productCategories?: ProductCategoryUpdateManyWithoutTenantsInput;
  productDepartments?: ProductDepartmentUpdateManyWithoutTenantsInput;
  productGroups?: ProductGroupUpdateManyWithoutTenantsInput;
  productTypes?: ProductTypeUpdateManyWithoutTenantsInput;
  productUnits?: ProductUnitUpdateManyWithoutTenantsInput;
  productVariants?: ProductVariantUpdateManyWithoutTenantsInput;
  productionAvailabilities?: ProductionAvailabilityUpdateManyWithoutTenantsInput;
  productionDocuments?: ProductionDocumentUpdateManyWithoutTenantsInput;
  productionOrders?: ProductionOrderUpdateManyWithoutTenantsInput;
  products?: ProductUpdateManyWithoutTenantsInput;
  purchaseDetails?: PurchaseDetailUpdateManyWithoutTenantsInput;
  purchasePriceTypes?: PurchasePriceTypeUpdateManyWithoutTenantsInput;
  purchaseReturnDetails?: PurchaseReturnDetailUpdateManyWithoutTenantsInput;
  purchaseReturns?: PurchaseReturnUpdateManyWithoutTenantsInput;
  purchases?: PurchaseUpdateManyWithoutTenantsInput;
  receiptVouchers?: ReceiptVoucherUpdateManyWithoutTenantsInput;
  resourceTypes?: ResourceTypeUpdateManyWithoutTenantsInput;
  resources?: ResourceUpdateManyWithoutTenantsInput;
  roleGroups?: RoleGroupUpdateManyWithoutTenantsInput;
  salaryItemGroups?: SalaryItemGroupUpdateManyWithoutTenantsInput;
  salaryItemTypes?: SalaryItemTypeUpdateManyWithoutTenantsInput;
  salaryItems?: SalaryItemUpdateManyWithoutTenantsInput;
  salaryLaws?: SalaryLawUpdateManyWithoutTenantsInput;
  saleDetails?: SaleDetailUpdateManyWithoutTenantsInput;
  saleOrderDetails?: SaleOrderDetailUpdateManyWithoutTenantsInput;
  saleOrders?: SaleOrderUpdateManyWithoutTenantsInput;
  salePayments?: SalePaymentUpdateManyWithoutTenantsInput;
  salePeople?: SalePersonUpdateManyWithoutTenantsInput;
  salePriceTypes?: SalePriceTypeUpdateManyWithoutTenantsInput;
  saleQuotationDetails?: SaleQuotationDetailUpdateManyWithoutTenantsInput;
  saleQuotations?: SaleQuotationUpdateManyWithoutTenantsInput;
  saleReturnDetails?: SaleReturnDetailUpdateManyWithoutTenantsInput;
  saleReturns?: SaleReturnUpdateManyWithoutTenantsInput;
  saleTaxes?: SaleTaxUpdateManyWithoutTenantsInput;
  saleTeams?: SaleTeamUpdateManyWithoutTenantsInput;
  sales?: SaleUpdateManyWithoutTenantsInput;
  scrapReasons?: ScrapReasonUpdateManyWithoutTenantsInput;
  settingGroups?: SettingGroupUpdateManyWithoutTenantsInput;
  settings?: SettingUpdateManyWithoutTenantsInput;
  shifts?: ShiftUpdateManyWithoutTenantsInput;
  shippingStatuses?: ShippingStatusUpdateManyWithoutTenantsInput;
  storeLocations?: StoreLocationUpdateManyWithoutTenantsInput;
  storeTypes?: StoreTypeUpdateManyWithoutTenantsInput;
  stores?: StoreUpdateManyWithoutTenantsInput;
  suppliers?: SupplierUpdateManyWithoutTenantsInput;
  tenancyName?: string;
  timeModes?: TimeModeUpdateManyWithoutTenantsInput;
  timeoffTypes?: TimeoffTypeUpdateManyWithoutTenantsInput;
  units?: UnitUpdateManyWithoutTenantsInput;
  users?: UserUpdateManyWithoutTenantsInput;
  voucherTypes?: VoucherTypeUpdateManyWithoutTenantsInput;
  workCenterRoutings?: WorkCenterRoutingUpdateManyWithoutTenantsInput;
  workCenters?: WorkCenterUpdateManyWithoutTenantsInput;
};
