import { AccountCreateNestedManyWithoutTenantsInput } from "./AccountCreateNestedManyWithoutTenantsInput";
import { ApplicationDependencyCreateNestedManyWithoutTenantsInput } from "./ApplicationDependencyCreateNestedManyWithoutTenantsInput";
import { ApplicationCreateNestedManyWithoutTenantsInput } from "./ApplicationCreateNestedManyWithoutTenantsInput";
import { AttributeValueCreateNestedManyWithoutTenantsInput } from "./AttributeValueCreateNestedManyWithoutTenantsInput";
import { AttributeCreateNestedManyWithoutTenantsInput } from "./AttributeCreateNestedManyWithoutTenantsInput";
import { BarcodeTypeCreateNestedManyWithoutTenantsInput } from "./BarcodeTypeCreateNestedManyWithoutTenantsInput";
import { BillOfMaterialDetailCreateNestedManyWithoutTenantsInput } from "./BillOfMaterialDetailCreateNestedManyWithoutTenantsInput";
import { BillOfMaterialTypeCreateNestedManyWithoutTenantsInput } from "./BillOfMaterialTypeCreateNestedManyWithoutTenantsInput";
import { BillOfMaterialCreateNestedManyWithoutTenantsInput } from "./BillOfMaterialCreateNestedManyWithoutTenantsInput";
import { CashRepositoryCreateNestedManyWithoutTenantsInput } from "./CashRepositoryCreateNestedManyWithoutTenantsInput";
import { CurrencyCreateNestedManyWithoutTenantsInput } from "./CurrencyCreateNestedManyWithoutTenantsInput";
import { CustomerCreateNestedManyWithoutTenantsInput } from "./CustomerCreateNestedManyWithoutTenantsInput";
import { EmployeeClassCreateNestedManyWithoutTenantsInput } from "./EmployeeClassCreateNestedManyWithoutTenantsInput";
import { EmployeeDepartmentCreateNestedManyWithoutTenantsInput } from "./EmployeeDepartmentCreateNestedManyWithoutTenantsInput";
import { EmployeeCreateNestedManyWithoutTenantsInput } from "./EmployeeCreateNestedManyWithoutTenantsInput";
import { InstallmentSaleFeeCreateNestedManyWithoutTenantsInput } from "./InstallmentSaleFeeCreateNestedManyWithoutTenantsInput";
import { InvoiceTypeCreateNestedManyWithoutTenantsInput } from "./InvoiceTypeCreateNestedManyWithoutTenantsInput";
import { OrderStatusCreateNestedManyWithoutTenantsInput } from "./OrderStatusCreateNestedManyWithoutTenantsInput";
import { PaymentTermCreateNestedManyWithoutTenantsInput } from "./PaymentTermCreateNestedManyWithoutTenantsInput";
import { PaymentTypeCreateNestedManyWithoutTenantsInput } from "./PaymentTypeCreateNestedManyWithoutTenantsInput";
import { PeriodCreateNestedManyWithoutTenantsInput } from "./PeriodCreateNestedManyWithoutTenantsInput";
import { PrintTemplateContentCreateNestedManyWithoutTenantsInput } from "./PrintTemplateContentCreateNestedManyWithoutTenantsInput";
import { PrintTemplateGroupCreateNestedManyWithoutTenantsInput } from "./PrintTemplateGroupCreateNestedManyWithoutTenantsInput";
import { PrintTemplateCreateNestedManyWithoutTenantsInput } from "./PrintTemplateCreateNestedManyWithoutTenantsInput";
import { ProductBarcodeCreateNestedManyWithoutTenantsInput } from "./ProductBarcodeCreateNestedManyWithoutTenantsInput";
import { ProductCategoryCreateNestedManyWithoutTenantsInput } from "./ProductCategoryCreateNestedManyWithoutTenantsInput";
import { ProductDepartmentCreateNestedManyWithoutTenantsInput } from "./ProductDepartmentCreateNestedManyWithoutTenantsInput";
import { ProductGroupCreateNestedManyWithoutTenantsInput } from "./ProductGroupCreateNestedManyWithoutTenantsInput";
import { ProductTypeCreateNestedManyWithoutTenantsInput } from "./ProductTypeCreateNestedManyWithoutTenantsInput";
import { ProductUnitCreateNestedManyWithoutTenantsInput } from "./ProductUnitCreateNestedManyWithoutTenantsInput";
import { ProductVariantCreateNestedManyWithoutTenantsInput } from "./ProductVariantCreateNestedManyWithoutTenantsInput";
import { ProductionAvailabilityCreateNestedManyWithoutTenantsInput } from "./ProductionAvailabilityCreateNestedManyWithoutTenantsInput";
import { ProductionDocumentCreateNestedManyWithoutTenantsInput } from "./ProductionDocumentCreateNestedManyWithoutTenantsInput";
import { ProductionOrderCreateNestedManyWithoutTenantsInput } from "./ProductionOrderCreateNestedManyWithoutTenantsInput";
import { ProductCreateNestedManyWithoutTenantsInput } from "./ProductCreateNestedManyWithoutTenantsInput";
import { PurchaseDetailCreateNestedManyWithoutTenantsInput } from "./PurchaseDetailCreateNestedManyWithoutTenantsInput";
import { PurchasePriceTypeCreateNestedManyWithoutTenantsInput } from "./PurchasePriceTypeCreateNestedManyWithoutTenantsInput";
import { PurchaseReturnDetailCreateNestedManyWithoutTenantsInput } from "./PurchaseReturnDetailCreateNestedManyWithoutTenantsInput";
import { PurchaseReturnCreateNestedManyWithoutTenantsInput } from "./PurchaseReturnCreateNestedManyWithoutTenantsInput";
import { PurchaseCreateNestedManyWithoutTenantsInput } from "./PurchaseCreateNestedManyWithoutTenantsInput";
import { ResourceTypeCreateNestedManyWithoutTenantsInput } from "./ResourceTypeCreateNestedManyWithoutTenantsInput";
import { ResourceCreateNestedManyWithoutTenantsInput } from "./ResourceCreateNestedManyWithoutTenantsInput";
import { RoleGroupCreateNestedManyWithoutTenantsInput } from "./RoleGroupCreateNestedManyWithoutTenantsInput";
import { SalaryItemGroupCreateNestedManyWithoutTenantsInput } from "./SalaryItemGroupCreateNestedManyWithoutTenantsInput";
import { SalaryItemTypeCreateNestedManyWithoutTenantsInput } from "./SalaryItemTypeCreateNestedManyWithoutTenantsInput";
import { SalaryItemCreateNestedManyWithoutTenantsInput } from "./SalaryItemCreateNestedManyWithoutTenantsInput";
import { SalaryLawCreateNestedManyWithoutTenantsInput } from "./SalaryLawCreateNestedManyWithoutTenantsInput";
import { SaleDetailCreateNestedManyWithoutTenantsInput } from "./SaleDetailCreateNestedManyWithoutTenantsInput";
import { SalePersonCreateNestedManyWithoutTenantsInput } from "./SalePersonCreateNestedManyWithoutTenantsInput";
import { SalePriceTypeCreateNestedManyWithoutTenantsInput } from "./SalePriceTypeCreateNestedManyWithoutTenantsInput";
import { SaleQuotationDetailCreateNestedManyWithoutTenantsInput } from "./SaleQuotationDetailCreateNestedManyWithoutTenantsInput";
import { SaleQuotationCreateNestedManyWithoutTenantsInput } from "./SaleQuotationCreateNestedManyWithoutTenantsInput";
import { SaleReturnDetailCreateNestedManyWithoutTenantsInput } from "./SaleReturnDetailCreateNestedManyWithoutTenantsInput";
import { SaleReturnCreateNestedManyWithoutTenantsInput } from "./SaleReturnCreateNestedManyWithoutTenantsInput";
import { SaleTaxCreateNestedManyWithoutTenantsInput } from "./SaleTaxCreateNestedManyWithoutTenantsInput";
import { SaleTeamCreateNestedManyWithoutTenantsInput } from "./SaleTeamCreateNestedManyWithoutTenantsInput";
import { SaleCreateNestedManyWithoutTenantsInput } from "./SaleCreateNestedManyWithoutTenantsInput";
import { ScrapReasonCreateNestedManyWithoutTenantsInput } from "./ScrapReasonCreateNestedManyWithoutTenantsInput";
import { StoreCreateNestedManyWithoutTenantsInput } from "./StoreCreateNestedManyWithoutTenantsInput";
import { SupplierCreateNestedManyWithoutTenantsInput } from "./SupplierCreateNestedManyWithoutTenantsInput";
import { UnitCreateNestedManyWithoutTenantsInput } from "./UnitCreateNestedManyWithoutTenantsInput";
import { UserCreateNestedManyWithoutTenantsInput } from "./UserCreateNestedManyWithoutTenantsInput";
import { WorkCenterRoutingCreateNestedManyWithoutTenantsInput } from "./WorkCenterRoutingCreateNestedManyWithoutTenantsInput";
import { WorkCenterCreateNestedManyWithoutTenantsInput } from "./WorkCenterCreateNestedManyWithoutTenantsInput";

export type TenantCreateInput = {
  accounts?: AccountCreateNestedManyWithoutTenantsInput;
  applicationDependencies?: ApplicationDependencyCreateNestedManyWithoutTenantsInput;
  applications?: ApplicationCreateNestedManyWithoutTenantsInput;
  attributeValues?: AttributeValueCreateNestedManyWithoutTenantsInput;
  attributes?: AttributeCreateNestedManyWithoutTenantsInput;
  barcodeTypes?: BarcodeTypeCreateNestedManyWithoutTenantsInput;
  billOfMaterialDetails?: BillOfMaterialDetailCreateNestedManyWithoutTenantsInput;
  billOfMaterialTypes?: BillOfMaterialTypeCreateNestedManyWithoutTenantsInput;
  billOfMaterials?: BillOfMaterialCreateNestedManyWithoutTenantsInput;
  cashRepositories?: CashRepositoryCreateNestedManyWithoutTenantsInput;
  code?: string | null;
  creatorUserId?: string | null;
  currencies?: CurrencyCreateNestedManyWithoutTenantsInput;
  customers?: CustomerCreateNestedManyWithoutTenantsInput;
  description?: string | null;
  email?: string | null;
  employeeClasses?: EmployeeClassCreateNestedManyWithoutTenantsInput;
  employeeDepartments?: EmployeeDepartmentCreateNestedManyWithoutTenantsInput;
  employees?: EmployeeCreateNestedManyWithoutTenantsInput;
  installmentSaleFees?: InstallmentSaleFeeCreateNestedManyWithoutTenantsInput;
  invoiceTypes?: InvoiceTypeCreateNestedManyWithoutTenantsInput;
  isActive: boolean;
  lastModifierUserIdl?: string | null;
  name: string;
  normalizedName: string;
  note?: string | null;
  orderStatuses?: OrderStatusCreateNestedManyWithoutTenantsInput;
  paymentTerms?: PaymentTermCreateNestedManyWithoutTenantsInput;
  paymentTypes?: PaymentTypeCreateNestedManyWithoutTenantsInput;
  periods?: PeriodCreateNestedManyWithoutTenantsInput;
  printTemplateContents?: PrintTemplateContentCreateNestedManyWithoutTenantsInput;
  printTemplateGroups?: PrintTemplateGroupCreateNestedManyWithoutTenantsInput;
  printTemplates?: PrintTemplateCreateNestedManyWithoutTenantsInput;
  productBarcodes?: ProductBarcodeCreateNestedManyWithoutTenantsInput;
  productCategories?: ProductCategoryCreateNestedManyWithoutTenantsInput;
  productDepartments?: ProductDepartmentCreateNestedManyWithoutTenantsInput;
  productGroups?: ProductGroupCreateNestedManyWithoutTenantsInput;
  productTypes?: ProductTypeCreateNestedManyWithoutTenantsInput;
  productUnits?: ProductUnitCreateNestedManyWithoutTenantsInput;
  productVariants?: ProductVariantCreateNestedManyWithoutTenantsInput;
  productionAvailabilities?: ProductionAvailabilityCreateNestedManyWithoutTenantsInput;
  productionDocuments?: ProductionDocumentCreateNestedManyWithoutTenantsInput;
  productionOrders?: ProductionOrderCreateNestedManyWithoutTenantsInput;
  products?: ProductCreateNestedManyWithoutTenantsInput;
  purchaseDetails?: PurchaseDetailCreateNestedManyWithoutTenantsInput;
  purchasePriceTypes?: PurchasePriceTypeCreateNestedManyWithoutTenantsInput;
  purchaseReturnDetails?: PurchaseReturnDetailCreateNestedManyWithoutTenantsInput;
  purchaseReturns?: PurchaseReturnCreateNestedManyWithoutTenantsInput;
  purchases?: PurchaseCreateNestedManyWithoutTenantsInput;
  resourceTypes?: ResourceTypeCreateNestedManyWithoutTenantsInput;
  resources?: ResourceCreateNestedManyWithoutTenantsInput;
  roleGroups?: RoleGroupCreateNestedManyWithoutTenantsInput;
  salaryItemGroups?: SalaryItemGroupCreateNestedManyWithoutTenantsInput;
  salaryItemTypes?: SalaryItemTypeCreateNestedManyWithoutTenantsInput;
  salaryItems?: SalaryItemCreateNestedManyWithoutTenantsInput;
  salaryLaws?: SalaryLawCreateNestedManyWithoutTenantsInput;
  saleDetails?: SaleDetailCreateNestedManyWithoutTenantsInput;
  salePeople?: SalePersonCreateNestedManyWithoutTenantsInput;
  salePriceTypes?: SalePriceTypeCreateNestedManyWithoutTenantsInput;
  saleQuotationDetails?: SaleQuotationDetailCreateNestedManyWithoutTenantsInput;
  saleQuotations?: SaleQuotationCreateNestedManyWithoutTenantsInput;
  saleReturnDetails?: SaleReturnDetailCreateNestedManyWithoutTenantsInput;
  saleReturns?: SaleReturnCreateNestedManyWithoutTenantsInput;
  saleTaxes?: SaleTaxCreateNestedManyWithoutTenantsInput;
  saleTeams?: SaleTeamCreateNestedManyWithoutTenantsInput;
  sales?: SaleCreateNestedManyWithoutTenantsInput;
  scrapReasons?: ScrapReasonCreateNestedManyWithoutTenantsInput;
  stores?: StoreCreateNestedManyWithoutTenantsInput;
  suppliers?: SupplierCreateNestedManyWithoutTenantsInput;
  tenancyName: string;
  units?: UnitCreateNestedManyWithoutTenantsInput;
  users?: UserCreateNestedManyWithoutTenantsInput;
  workCenterRoutings?: WorkCenterRoutingCreateNestedManyWithoutTenantsInput;
  workCenters?: WorkCenterCreateNestedManyWithoutTenantsInput;
};
