import { AttendanceListRelationFilter } from "../attendance/AttendanceListRelationFilter";
import { BonusRequestListRelationFilter } from "../bonusRequest/BonusRequestListRelationFilter";
import { CheckInOutListRelationFilter } from "../checkInOut/CheckInOutListRelationFilter";
import { DailyMovementRequestListRelationFilter } from "../dailyMovementRequest/DailyMovementRequestListRelationFilter";
import { DayOffRequestListRelationFilter } from "../dayOffRequest/DayOffRequestListRelationFilter";
import { EmployeeDepartmentListRelationFilter } from "../employeeDepartment/EmployeeDepartmentListRelationFilter";
import { EmployeeGroupListRelationFilter } from "../employeeGroup/EmployeeGroupListRelationFilter";
import { EmployeeRoleListRelationFilter } from "../employeeRole/EmployeeRoleListRelationFilter";
import { EmployeeListRelationFilter } from "../employee/EmployeeListRelationFilter";
import { MachineListRelationFilter } from "../machine/MachineListRelationFilter";
import { FiscalMonthListRelationFilter } from "../fiscalMonth/FiscalMonthListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { JobTitleListRelationFilter } from "../jobTitle/JobTitleListRelationFilter";
import { LeaveRequestTypeListRelationFilter } from "../leaveRequestType/LeaveRequestTypeListRelationFilter";
import { LeaveRequestListRelationFilter } from "../leaveRequest/LeaveRequestListRelationFilter";
import { OverNightRequestListRelationFilter } from "../overNightRequest/OverNightRequestListRelationFilter";
import { ScrapReasonListRelationFilter } from "../scrapReason/ScrapReasonListRelationFilter";
import { TradingSummaryListRelationFilter } from "../tradingSummary/TradingSummaryListRelationFilter";
import { WorkCenterAlternativeListRelationFilter } from "../workCenterAlternative/WorkCenterAlternativeListRelationFilter";
import { WorkCenterCapacityListRelationFilter } from "../workCenterCapacity/WorkCenterCapacityListRelationFilter";
import { WorkCenterProductivityListRelationFilter } from "../workCenterProductivity/WorkCenterProductivityListRelationFilter";
import { WorkCenterProductivityLossTypeListRelationFilter } from "../workCenterProductivityLossType/WorkCenterProductivityLossTypeListRelationFilter";
import { WorkCenterProductivityLossListRelationFilter } from "../workCenterProductivityLoss/WorkCenterProductivityLossListRelationFilter";
import { WorkCenterRoutingListRelationFilter } from "../workCenterRouting/WorkCenterRoutingListRelationFilter";
import { WorkCenterTagListRelationFilter } from "../workCenterTag/WorkCenterTagListRelationFilter";
import { WorkCenterWorkCenterTagListRelationFilter } from "../workCenterWorkCenterTag/WorkCenterWorkCenterTagListRelationFilter";
import { WorkCenterListRelationFilter } from "../workCenter/WorkCenterListRelationFilter";
import { WorkOrderDependencyListRelationFilter } from "../workOrderDependency/WorkOrderDependencyListRelationFilter";
import { WorkOrderRoutingListRelationFilter } from "../workOrderRouting/WorkOrderRoutingListRelationFilter";
import { WorkOrderStatusListRelationFilter } from "../workOrderStatus/WorkOrderStatusListRelationFilter";
import { WorkOrderListRelationFilter } from "../workOrder/WorkOrderListRelationFilter";
import { WorkSheetTypeListRelationFilter } from "../workSheetType/WorkSheetTypeListRelationFilter";

export type TenantWhereInput = {
  attendances?: AttendanceListRelationFilter;
  bonusRequests?: BonusRequestListRelationFilter;
  checkInOuts?: CheckInOutListRelationFilter;
  dailyMovements?: DailyMovementRequestListRelationFilter;
  dayOffs?: DayOffRequestListRelationFilter;
  employeeDepartments?: EmployeeDepartmentListRelationFilter;
  employeeGroups?: EmployeeGroupListRelationFilter;
  employeeRoles?: EmployeeRoleListRelationFilter;
  employees?: EmployeeListRelationFilter;
  fingerprintMachines?: MachineListRelationFilter;
  fiscalMonths?: FiscalMonthListRelationFilter;
  id?: StringFilter;
  jobTitles?: JobTitleListRelationFilter;
  leaveRequestTypes?: LeaveRequestTypeListRelationFilter;
  leaveRequests?: LeaveRequestListRelationFilter;
  overNights?: OverNightRequestListRelationFilter;
  scrapReasons?: ScrapReasonListRelationFilter;
  tradingSummaries?: TradingSummaryListRelationFilter;
  workCenterAlternatives?: WorkCenterAlternativeListRelationFilter;
  workCenterCapacities?: WorkCenterCapacityListRelationFilter;
  workCenterProductivities?: WorkCenterProductivityListRelationFilter;
  workCenterProductivityLossTypes?: WorkCenterProductivityLossTypeListRelationFilter;
  workCenterProductivityLosses?: WorkCenterProductivityLossListRelationFilter;
  workCenterRoutings?: WorkCenterRoutingListRelationFilter;
  workCenterTags?: WorkCenterTagListRelationFilter;
  workCenterWorkCenterTags?: WorkCenterWorkCenterTagListRelationFilter;
  workCenters?: WorkCenterListRelationFilter;
  workOrderDependencies?: WorkOrderDependencyListRelationFilter;
  workOrderRoutings?: WorkOrderRoutingListRelationFilter;
  workOrderStatuses?: WorkOrderStatusListRelationFilter;
  workOrders?: WorkOrderListRelationFilter;
  workSheetTypes?: WorkSheetTypeListRelationFilter;
};
