import { Attendance } from "../attendance/Attendance";
import { BonusRequest } from "../bonusRequest/BonusRequest";
import { CheckInOut } from "../checkInOut/CheckInOut";
import { DailyMovementRequest } from "../dailyMovementRequest/DailyMovementRequest";
import { DayOffRequest } from "../dayOffRequest/DayOffRequest";
import { EmployeeDepartment } from "../employeeDepartment/EmployeeDepartment";
import { EmployeeGroup } from "../employeeGroup/EmployeeGroup";
import { EmployeeRole } from "../employeeRole/EmployeeRole";
import { Employee } from "../employee/Employee";
import { Machine } from "../machine/Machine";
import { FiscalMonth } from "../fiscalMonth/FiscalMonth";
import { JobTitle } from "../jobTitle/JobTitle";
import { LeaveRequestType } from "../leaveRequestType/LeaveRequestType";
import { LeaveRequest } from "../leaveRequest/LeaveRequest";
import { OverNightRequest } from "../overNightRequest/OverNightRequest";
import { ScrapReason } from "../scrapReason/ScrapReason";
import { TradingSummary } from "../tradingSummary/TradingSummary";
import { WorkCenterAlternative } from "../workCenterAlternative/WorkCenterAlternative";
import { WorkCenterCapacity } from "../workCenterCapacity/WorkCenterCapacity";
import { WorkCenterProductivity } from "../workCenterProductivity/WorkCenterProductivity";
import { WorkCenterProductivityLossType } from "../workCenterProductivityLossType/WorkCenterProductivityLossType";
import { WorkCenterProductivityLoss } from "../workCenterProductivityLoss/WorkCenterProductivityLoss";
import { WorkCenterRouting } from "../workCenterRouting/WorkCenterRouting";
import { WorkCenterTag } from "../workCenterTag/WorkCenterTag";
import { WorkCenterWorkCenterTag } from "../workCenterWorkCenterTag/WorkCenterWorkCenterTag";
import { WorkCenter } from "../workCenter/WorkCenter";
import { WorkOrderDependency } from "../workOrderDependency/WorkOrderDependency";
import { WorkOrderRouting } from "../workOrderRouting/WorkOrderRouting";
import { WorkOrderStatus } from "../workOrderStatus/WorkOrderStatus";
import { WorkOrder } from "../workOrder/WorkOrder";
import { WorkSheetType } from "../workSheetType/WorkSheetType";

export type Tenant = {
  attendances?: Array<Attendance>;
  bonusRequests?: Array<BonusRequest>;
  checkInOuts?: Array<CheckInOut>;
  createdAt: Date;
  dailyMovements?: Array<DailyMovementRequest>;
  dayOffs?: Array<DayOffRequest>;
  employeeDepartments?: Array<EmployeeDepartment>;
  employeeGroups?: Array<EmployeeGroup>;
  employeeRoles?: Array<EmployeeRole>;
  employees?: Array<Employee>;
  fingerprintMachines?: Array<Machine>;
  fiscalMonths?: Array<FiscalMonth>;
  id: string;
  jobTitles?: Array<JobTitle>;
  leaveRequestTypes?: Array<LeaveRequestType>;
  leaveRequests?: Array<LeaveRequest>;
  overNights?: Array<OverNightRequest>;
  scrapReasons?: Array<ScrapReason>;
  tradingSummaries?: Array<TradingSummary>;
  updatedAt: Date;
  workCenterAlternatives?: Array<WorkCenterAlternative>;
  workCenterCapacities?: Array<WorkCenterCapacity>;
  workCenterProductivities?: Array<WorkCenterProductivity>;
  workCenterProductivityLossTypes?: Array<WorkCenterProductivityLossType>;
  workCenterProductivityLosses?: Array<WorkCenterProductivityLoss>;
  workCenterRoutings?: Array<WorkCenterRouting>;
  workCenterTags?: Array<WorkCenterTag>;
  workCenterWorkCenterTags?: Array<WorkCenterWorkCenterTag>;
  workCenters?: Array<WorkCenter>;
  workOrderDependencies?: Array<WorkOrderDependency>;
  workOrderRoutings?: Array<WorkOrderRouting>;
  workOrderStatuses?: Array<WorkOrderStatus>;
  workOrders?: Array<WorkOrder>;
  workSheetTypes?: Array<WorkSheetType>;
};
