import { ProductGroupWhereUniqueInput } from "../productGroup/ProductGroupWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { UnitWhereUniqueInput } from "../unit/UnitWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { ProductCategoryWhereUniqueInput } from "../productCategory/ProductCategoryWhereUniqueInput";
import { ProductDepartmentWhereUniqueInput } from "../productDepartment/ProductDepartmentWhereUniqueInput";
import { ProductTypeWhereUniqueInput } from "../productType/ProductTypeWhereUniqueInput";
import { FloatFilter } from "../../util/FloatFilter";
import { SaleTaxWhereUniqueInput } from "../saleTax/SaleTaxWhereUniqueInput";

export type ProductWhereInput = {
  ProductGroupId?: ProductGroupWhereUniqueInput;
  barcode?: StringNullableFilter;
  canExpire?: BooleanFilter;
  code?: StringNullableFilter;
  costPrice?: DecimalNullableFilter;
  costPriceIncludesTax?: BooleanNullableFilter;
  currentStockQuantity?: DecimalFilter;
  daysToManufacture?: DecimalNullableFilter;
  defaultStoreId?: StoreWhereUniqueInput;
  defaultUnitId?: UnitWhereUniqueInput;
  description?: StringNullableFilter;
  discontinuedDate?: DateTimeNullableFilter;
  discountRate?: DecimalNullableFilter;
  expireAlarmInDays?: IntNullableFilter;
  expireIsDefaultAfterDaysFromPurchase?: IntNullableFilter;
  firstStockQuantity?: DecimalNullableFilter;
  id?: StringFilter;
  isActive?: BooleanFilter;
  isCompound?: BooleanNullableFilter;
  isFavorite?: BooleanFilter;
  maintainInventory?: BooleanFilter;
  minimumSalePrice?: DecimalNullableFilter;
  name?: StringFilter;
  normalizedName?: StringFilter;
  photo?: JsonFilter;
  productCategoryId?: ProductCategoryWhereUniqueInput;
  productDepartmentId?: ProductDepartmentWhereUniqueInput;
  productTypeId?: ProductTypeWhereUniqueInput;
  profitRate?: DecimalNullableFilter;
  reorderQuantity?: DecimalNullableFilter;
  salePrice?: FloatFilter;
  salePriceIncludesTax?: BooleanNullableFilter;
  saleTaxId?: SaleTaxWhereUniqueInput;
};
