import { BillOfMaterialDetail } from "../billOfMaterialDetail/BillOfMaterialDetail";
import { BillOfMaterial } from "../billOfMaterial/BillOfMaterial";
import { Decimal } from "decimal.js";
import { Store } from "../store/Store";
import { Unit } from "../unit/Unit";
import { JsonValue } from "type-fest";
import { ProductBarcode } from "../productBarcode/ProductBarcode";
import { ProductCategory } from "../productCategory/ProductCategory";
import { ProductDepartment } from "../productDepartment/ProductDepartment";
import { ProductGroup } from "../productGroup/ProductGroup";
import { ProductType } from "../productType/ProductType";
import { ProductVariant } from "../productVariant/ProductVariant";
import { ProductionOrder } from "../productionOrder/ProductionOrder";
import { SaleTax } from "../saleTax/SaleTax";

export type Product = {
  barcode: string | null;
  billOfMaterialDetails?: Array<BillOfMaterialDetail>;
  billOfMaterials?: Array<BillOfMaterial>;
  canExpire: boolean;
  code: string | null;
  costPrice: Decimal;
  costPriceIncludesTax: boolean | null;
  createdAt: Date;
  currentStockQuantity: Decimal;
  daysToManufacture: number | null;
  defaultStoreId?: Store | null;
  defaultUnitId?: Unit;
  description: string | null;
  discontinuedDate: Date | null;
  discountRate: Decimal | null;
  expireAlarmInDays: number | null;
  expireIsDefaultAfterDaysFromPurchase: number | null;
  firstStockQuantity: Decimal | null;
  id: string;
  isActive: boolean;
  isCompound: boolean | null;
  isFavorite: boolean;
  maintainInventory: boolean;
  minimumSalePrice: Decimal | null;
  name: string;
  normalizedName: string;
  note: string | null;
  photo: JsonValue;
  productBarcodes?: Array<ProductBarcode>;
  productCategoryId?: ProductCategory | null;
  productDepartmentId?: ProductDepartment | null;
  productGroupId?: ProductGroup | null;
  productTypeId?: ProductType;
  productVariants?: Array<ProductVariant>;
  productionOrders?: Array<ProductionOrder>;
  profitRate: Decimal | null;
  reorderQuantity: Decimal | null;
  salePrice: Decimal;
  salePriceIncludesTax: boolean;
  saleTaxId?: SaleTax | null;
  updatedAt: Date;
};
