import { ProductGroup } from "../productGroup/ProductGroup";
import { Decimal } from "decimal.js";
import { Store } from "../store/Store";
import { Unit } from "../unit/Unit";
import { JsonValue } from "type-fest";
import { ProductCategory } from "../productCategory/ProductCategory";
import { ProductDepartment } from "../productDepartment/ProductDepartment";
import { ProductType } from "../productType/ProductType";
import { SaleTax } from "../saleTax/SaleTax";

export type Product = {
  ProductGroupId?: ProductGroup | null;
  barcode: string | null;
  canExpire: boolean;
  code: string | null;
  costPrice: Decimal | null;
  costPriceIncludesTax: boolean | null;
  createdAt: Date;
  currentStockQuantity: Decimal;
  daysToManufacture: Decimal | null;
  defaultStoreId?: Store;
  defaultUnitId?: Unit;
  description: string | null;
  discontinuedDate: Date | null;
  discountRate: Decimal | null;
  expireAlarmInDays: number | null;
  expireIsDefaultAfterDaysFromPurchase: number | null;
  firstStockQuantity: Decimal | null;
  id: string;
  isActive: boolean;
  isCompound: boolean | null;
  isFavorite: boolean;
  maintainInventory: boolean;
  minimumSalePrice: Decimal | null;
  name: string;
  normalizedName: string;
  photo: JsonValue;
  productCategoryId?: ProductCategory | null;
  productDepartmentId?: ProductDepartment | null;
  productTypeId?: ProductType;
  profitRate: Decimal | null;
  reorderQuantity: Decimal | null;
  salePrice: number;
  salePriceIncludesTax: boolean | null;
  saleTaxId?: SaleTax | null;
  updatedAt: Date;
};
