import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BillOfMaterialDetailListRelationFilter } from "../billOfMaterialDetail/BillOfMaterialDetailListRelationFilter";
import { BillOfMaterialListRelationFilter } from "../billOfMaterial/BillOfMaterialListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalFilter } from "../../util/DecimalFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { UnitWhereUniqueInput } from "../unit/UnitWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { ProductBarcodeListRelationFilter } from "../productBarcode/ProductBarcodeListRelationFilter";
import { ProductCategoryWhereUniqueInput } from "../productCategory/ProductCategoryWhereUniqueInput";
import { ProductDepartmentWhereUniqueInput } from "../productDepartment/ProductDepartmentWhereUniqueInput";
import { ProductGroupWhereUniqueInput } from "../productGroup/ProductGroupWhereUniqueInput";
import { ProductTypeWhereUniqueInput } from "../productType/ProductTypeWhereUniqueInput";
import { ProductVariantListRelationFilter } from "../productVariant/ProductVariantListRelationFilter";
import { ProductionOrderListRelationFilter } from "../productionOrder/ProductionOrderListRelationFilter";
import { SaleTaxWhereUniqueInput } from "../saleTax/SaleTaxWhereUniqueInput";

export type ProductWhereInput = {
  barcode?: StringNullableFilter;
  billOfMaterialDetails?: BillOfMaterialDetailListRelationFilter;
  billOfMaterials?: BillOfMaterialListRelationFilter;
  canExpire?: BooleanFilter;
  code?: StringNullableFilter;
  costPrice?: DecimalFilter;
  costPriceIncludesTax?: BooleanNullableFilter;
  currentStockQuantity?: DecimalFilter;
  daysToManufacture?: IntNullableFilter;
  defaultStoreId?: StoreWhereUniqueInput;
  defaultUnitId?: UnitWhereUniqueInput;
  description?: StringNullableFilter;
  discontinuedDate?: DateTimeNullableFilter;
  discountRate?: DecimalNullableFilter;
  expireAlarmInDays?: IntNullableFilter;
  expireIsDefaultAfterDaysFromPurchase?: IntNullableFilter;
  firstStockQuantity?: DecimalNullableFilter;
  id?: StringFilter;
  isActive?: BooleanFilter;
  isCompound?: BooleanNullableFilter;
  isFavorite?: BooleanFilter;
  maintainInventory?: BooleanFilter;
  minimumSalePrice?: DecimalNullableFilter;
  name?: StringFilter;
  normalizedName?: StringFilter;
  note?: StringNullableFilter;
  photo?: JsonFilter;
  productBarcodes?: ProductBarcodeListRelationFilter;
  productCategoryId?: ProductCategoryWhereUniqueInput;
  productDepartmentId?: ProductDepartmentWhereUniqueInput;
  productGroupId?: ProductGroupWhereUniqueInput;
  productTypeId?: ProductTypeWhereUniqueInput;
  productVariants?: ProductVariantListRelationFilter;
  productionOrders?: ProductionOrderListRelationFilter;
  profitRate?: DecimalNullableFilter;
  reorderQuantity?: DecimalNullableFilter;
  salePrice?: DecimalFilter;
  salePriceIncludesTax?: BooleanFilter;
  saleTaxId?: SaleTaxWhereUniqueInput;
};
