import { SortOrder } from "../../util/SortOrder";

export type ProductOrderByInput = {
  barcode?: SortOrder;
  canExpire?: SortOrder;
  code?: SortOrder;
  costPrice?: SortOrder;
  costPriceIncludesTax?: SortOrder;
  createdAt?: SortOrder;
  currentStockQuantity?: SortOrder;
  daysToManufacture?: SortOrder;
  defaultStoreIdId?: SortOrder;
  defaultUnitIdId?: SortOrder;
  description?: SortOrder;
  discontinuedDate?: SortOrder;
  discountRate?: SortOrder;
  expireAlarmInDays?: SortOrder;
  expireIsDefaultAfterDaysFromPurchase?: SortOrder;
  firstStockQuantity?: SortOrder;
  id?: SortOrder;
  isActive?: SortOrder;
  isCompound?: SortOrder;
  isFavorite?: SortOrder;
  maintainInventory?: SortOrder;
  minimumSalePrice?: SortOrder;
  name?: SortOrder;
  normalizedName?: SortOrder;
  note?: SortOrder;
  photo?: SortOrder;
  productCategoryIdId?: SortOrder;
  productDepartmentIdId?: SortOrder;
  productGroupIdId?: SortOrder;
  productTypeIdId?: SortOrder;
  profitRate?: SortOrder;
  reorderQuantity?: SortOrder;
  salePrice?: SortOrder;
  salePriceIncludesTax?: SortOrder;
  saleTaxIdId?: SortOrder;
  updatedAt?: SortOrder;
};
