import { ProductGroupWhereUniqueInput } from "../productGroup/ProductGroupWhereUniqueInput";
import { Decimal } from "decimal.js";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { UnitWhereUniqueInput } from "../unit/UnitWhereUniqueInput";
import { InputJsonValue } from "../../types";
import { ProductCategoryWhereUniqueInput } from "../productCategory/ProductCategoryWhereUniqueInput";
import { ProductDepartmentWhereUniqueInput } from "../productDepartment/ProductDepartmentWhereUniqueInput";
import { ProductTypeWhereUniqueInput } from "../productType/ProductTypeWhereUniqueInput";
import { SaleTaxWhereUniqueInput } from "../saleTax/SaleTaxWhereUniqueInput";

export type ProductCreateInput = {
  ProductGroupId?: ProductGroupWhereUniqueInput | null;
  barcode?: string | null;
  canExpire: boolean;
  code?: string | null;
  costPrice?: Decimal | null;
  costPriceIncludesTax?: boolean | null;
  currentStockQuantity: Decimal;
  daysToManufacture?: Decimal | null;
  defaultStoreId: StoreWhereUniqueInput;
  defaultUnitId: UnitWhereUniqueInput;
  description?: string | null;
  discontinuedDate?: Date | null;
  discountRate?: Decimal | null;
  expireAlarmInDays?: number | null;
  expireIsDefaultAfterDaysFromPurchase?: number | null;
  firstStockQuantity?: Decimal | null;
  isActive: boolean;
  isCompound?: boolean | null;
  isFavorite: boolean;
  maintainInventory: boolean;
  minimumSalePrice?: Decimal | null;
  name: string;
  normalizedName: string;
  photo?: InputJsonValue;
  productCategoryId?: ProductCategoryWhereUniqueInput | null;
  productDepartmentId?: ProductDepartmentWhereUniqueInput | null;
  productTypeId: ProductTypeWhereUniqueInput;
  profitRate?: Decimal | null;
  reorderQuantity?: Decimal | null;
  salePrice: number;
  salePriceIncludesTax?: boolean | null;
  saleTaxId?: SaleTaxWhereUniqueInput | null;
};
