import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AccountWhereUniqueInput } from "../account/AccountWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { StringFilter } from "../../util/StringFilter";
import { ProductGroupWhereUniqueInput } from "./ProductGroupWhereUniqueInput";
import { ProductGroupListRelationFilter } from "./ProductGroupListRelationFilter";
import { ProductListRelationFilter } from "../product/ProductListRelationFilter";
import { SaleTaxWhereUniqueInput } from "../saleTax/SaleTaxWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type ProductGroupWhereInput = {
  code?: StringNullableFilter;
  costOfGoodsSoldAccount?: AccountWhereUniqueInput;
  description?: StringNullableFilter;
  excludeFromPurchase?: BooleanFilter;
  excludeFromSale?: BooleanFilter;
  id?: StringFilter;
  inventoryAccount?: AccountWhereUniqueInput;
  isActive?: BooleanFilter;
  isDefault?: BooleanFilter;
  name?: StringFilter;
  normalizedName?: StringFilter;
  note?: StringNullableFilter;
  parentProductGroupId?: ProductGroupWhereUniqueInput;
  productGroups?: ProductGroupListRelationFilter;
  products?: ProductListRelationFilter;
  purchaseAccountId?: AccountWhereUniqueInput;
  purchaseDiscountAccountId?: AccountWhereUniqueInput;
  purchaseReturnAccountId?: AccountWhereUniqueInput;
  saleAccountId?: AccountWhereUniqueInput;
  saleDiscountAccountId?: AccountWhereUniqueInput;
  saleReturnAccountId?: AccountWhereUniqueInput;
  saleTaxId?: SaleTaxWhereUniqueInput;
  tenantId?: TenantWhereUniqueInput;
};
