import { ProductGroup } from "../productGroup/ProductGroup";
import { InstallmentSaleFee } from "../installmentSaleFee/InstallmentSaleFee";
import { SalePerson } from "../salePerson/SalePerson";
import { Tenant } from "../tenant/Tenant";

export type Account = {
  SaleReturnAccountProductGroups?: Array<ProductGroup>;
  accountNumber: string;
  aleAccountProductGroups?: Array<ProductGroup>;
  costOfGoodsSoldAccountProductGroups?: Array<ProductGroup>;
  createdAt: Date;
  description: string | null;
  id: string;
  installmentSaleFees?: Array<InstallmentSaleFee>;
  inventoryAccountProductGroups?: Array<ProductGroup>;
  isActive: boolean | null;
  isMasterAccount: boolean;
  name: string;
  normalizedName: string;
  note: string | null;
  parentAccountId?: Account | null;
  parentAccounts?: Array<Account>;
  purchaseAccountProductGroups?: Array<ProductGroup>;
  purchaseDiscountAccountProductGroups?: Array<ProductGroup>;
  purchaseReturnAccountProductGroups?: Array<ProductGroup>;
  saleDiscountAccountProductGroups?: Array<ProductGroup>;
  salePeople?: Array<SalePerson>;
  tenantId?: Tenant | null;
  updatedAt: Date;
};
