import { ProductGroupListRelationFilter } from "../productGroup/ProductGroupListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { InstallmentSaleFeeListRelationFilter } from "../installmentSaleFee/InstallmentSaleFeeListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";
import { AccountListRelationFilter } from "./AccountListRelationFilter";
import { SalePersonListRelationFilter } from "../salePerson/SalePersonListRelationFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type AccountWhereInput = {
  SaleReturnAccountProductGroups?: ProductGroupListRelationFilter;
  accountNumber?: StringFilter;
  aleAccountProductGroups?: ProductGroupListRelationFilter;
  costOfGoodsSoldAccountProductGroups?: ProductGroupListRelationFilter;
  description?: StringNullableFilter;
  id?: StringFilter;
  installmentSaleFees?: InstallmentSaleFeeListRelationFilter;
  inventoryAccountProductGroups?: ProductGroupListRelationFilter;
  isActive?: BooleanNullableFilter;
  isMasterAccount?: BooleanFilter;
  name?: StringFilter;
  normalizedName?: StringFilter;
  note?: StringNullableFilter;
  parentAccountId?: AccountWhereUniqueInput;
  parentAccounts?: AccountListRelationFilter;
  purchaseAccountProductGroups?: ProductGroupListRelationFilter;
  purchaseDiscountAccountProductGroups?: ProductGroupListRelationFilter;
  purchaseReturnAccountProductGroups?: ProductGroupListRelationFilter;
  saleDiscountAccountProductGroups?: ProductGroupListRelationFilter;
  salePeople?: SalePersonListRelationFilter;
  tenantId?: TenantWhereUniqueInput;
};
