import { ProductGroup } from "../productGroup/ProductGroup";
import { AccountCategory } from "../accountCategory/AccountCategory";
import { AccountType } from "../accountType/AccountType";
import { Currency } from "../currency/Currency";
import { InstallmentSaleFee } from "../installmentSaleFee/InstallmentSaleFee";

export type Account = {
  ProductGroupPurchaseReturnAccounts?: Array<ProductGroup>;
  ProductGroupSaleAccounts?: Array<ProductGroup>;
  accountCategory?: AccountCategory | null;
  accountNumber: string | null;
  accountTypeId?: AccountType;
  createdAt: Date;
  currencyId?: Currency;
  description: string | null;
  id: string;
  installmentSaleFees?: Array<InstallmentSaleFee>;
  isActive: boolean | null;
  isMasterAccount: boolean;
  isUnderRevision: boolean | null;
  name: string;
  normalizedName: string;
  note: string | null;
  parentAccountId: string | null;
  productGroupCostOfGoodsSoldAccounts?: Array<ProductGroup>;
  productGroupInventoryAccounts?: Array<ProductGroup>;
  productGroupPurchaseAccounts?: Array<ProductGroup>;
  productGroupPurchaseDiscountAccounts?: Array<ProductGroup>;
  productGroupSaleDiscountAccountIds?: Array<ProductGroup>;
  productGroupSaleReturnAccountIds?: Array<ProductGroup>;
  referenceNumber: string | null;
  updatedAt: Date;
};
