/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MachineService } from "../machine.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MachineCreateInput } from "./MachineCreateInput";
import { Machine } from "./Machine";
import { MachineFindManyArgs } from "./MachineFindManyArgs";
import { MachineWhereUniqueInput } from "./MachineWhereUniqueInput";
import { MachineUpdateInput } from "./MachineUpdateInput";
import { CheckInOutFindManyArgs } from "../../checkInOut/base/CheckInOutFindManyArgs";
import { CheckInOut } from "../../checkInOut/base/CheckInOut";
import { CheckInOutWhereUniqueInput } from "../../checkInOut/base/CheckInOutWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MachineControllerBase {
  constructor(
    protected readonly service: MachineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Machine })
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMachine(
    @common.Body() data: MachineCreateInput
  ): Promise<Machine> {
    return await this.service.createMachine({
      data: {
        ...data,

        tenantId: data.tenantId
          ? {
              connect: data.tenantId,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,
        ip: true,
        isAndroid: true,
        name: true,
        normalizedName: true,
        note: true,

        tenantId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Machine] })
  @ApiNestedQuery(MachineFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async machines(@common.Req() request: Request): Promise<Machine[]> {
    const args = plainToClass(MachineFindManyArgs, request.query);
    return this.service.machines({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,
        ip: true,
        isAndroid: true,
        name: true,
        normalizedName: true,
        note: true,

        tenantId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Machine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async machine(
    @common.Param() params: MachineWhereUniqueInput
  ): Promise<Machine | null> {
    const result = await this.service.machine({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,
        ip: true,
        isAndroid: true,
        name: true,
        normalizedName: true,
        note: true,

        tenantId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Machine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMachine(
    @common.Param() params: MachineWhereUniqueInput,
    @common.Body() data: MachineUpdateInput
  ): Promise<Machine | null> {
    try {
      return await this.service.updateMachine({
        where: params,
        data: {
          ...data,

          tenantId: data.tenantId
            ? {
                connect: data.tenantId,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,
          ip: true,
          isAndroid: true,
          name: true,
          normalizedName: true,
          note: true,

          tenantId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Machine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMachine(
    @common.Param() params: MachineWhereUniqueInput
  ): Promise<Machine | null> {
    try {
      return await this.service.deleteMachine({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,
          ip: true,
          isAndroid: true,
          name: true,
          normalizedName: true,
          note: true,

          tenantId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/checkInOuts")
  @ApiNestedQuery(CheckInOutFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CheckInOut",
    action: "read",
    possession: "any",
  })
  async findCheckInOuts(
    @common.Req() request: Request,
    @common.Param() params: MachineWhereUniqueInput
  ): Promise<CheckInOut[]> {
    const query = plainToClass(CheckInOutFindManyArgs, request.query);
    const results = await this.service.findCheckInOuts(params.id, {
      ...query,
      select: {
        approvedByUserId: {
          select: {
            id: true,
          },
        },

        checkDate: true,
        checkTime: true,
        checkType: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        isAppreoved: true,

        machine: {
          select: {
            id: true,
          },
        },

        note: true,

        tenantId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/checkInOuts")
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "update",
    possession: "any",
  })
  async connectCheckInOuts(
    @common.Param() params: MachineWhereUniqueInput,
    @common.Body() body: CheckInOutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checkInOuts: {
        connect: body,
      },
    };
    await this.service.updateMachine({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/checkInOuts")
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "update",
    possession: "any",
  })
  async updateCheckInOuts(
    @common.Param() params: MachineWhereUniqueInput,
    @common.Body() body: CheckInOutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checkInOuts: {
        set: body,
      },
    };
    await this.service.updateMachine({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/checkInOuts")
  @nestAccessControl.UseRoles({
    resource: "Machine",
    action: "update",
    possession: "any",
  })
  async disconnectCheckInOuts(
    @common.Param() params: MachineWhereUniqueInput,
    @common.Body() body: CheckInOutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checkInOuts: {
        disconnect: body,
      },
    };
    await this.service.updateMachine({
      where: params,
      data,
      select: { id: true },
    });
  }
}
