import { AccountTransactionWhereUniqueInput } from "../accountTransaction/AccountTransactionWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CurrencyWhereUniqueInput } from "../currency/CurrencyWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { VoucherTypeWhereUniqueInput } from "../voucherType/VoucherTypeWhereUniqueInput";

export type ReceiptVoucherWhereInput = {
  accountTransactionId?: AccountTransactionWhereUniqueInput;
  amount?: DecimalFilter;
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  chequeDueDate?: DateTimeNullableFilter;
  chequeNumber?: StringNullableFilter;
  chequeValue?: StringNullableFilter;
  currencyId?: CurrencyWhereUniqueInput;
  customerId?: CustomerWhereUniqueInput;
  employeeId?: EmployeeWhereUniqueInput;
  id?: StringFilter;
  isAcive?: BooleanFilter;
  note?: StringNullableFilter;
  receiptVoucherDate?: DateTimeFilter;
  sequence?: StringNullableFilter;
  statementReference?: StringNullableFilter;
  tenant?: TenantWhereUniqueInput;
  voucherTypeId?: VoucherTypeWhereUniqueInput;
  wasChequePaid?: BooleanFilter;
};
