/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { SalaryItemGroupWhereUniqueInput } from "../../salaryItemGroup/base/SalaryItemGroupWhereUniqueInput";
import { Type } from "class-transformer";
import { SalaryItemTypeWhereUniqueInput } from "../../salaryItemType/base/SalaryItemTypeWhereUniqueInput";
import { SalaryLawWhereUniqueInput } from "../../salaryLaw/base/SalaryLawWhereUniqueInput";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";

@InputType()
class SalaryItemCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  normalizedName!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: false,
    type: () => SalaryItemGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SalaryItemGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => SalaryItemGroupWhereUniqueInput, {
    nullable: true,
  })
  salaryItemGroupId?: SalaryItemGroupWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => SalaryItemTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SalaryItemTypeWhereUniqueInput)
  @Field(() => SalaryItemTypeWhereUniqueInput)
  salaryItemTypeId!: SalaryItemTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SalaryLawWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SalaryLawWhereUniqueInput)
  @IsOptional()
  @Field(() => SalaryLawWhereUniqueInput, {
    nullable: true,
  })
  salaryLawId?: SalaryLawWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @IsOptional()
  @Field(() => TenantWhereUniqueInput, {
    nullable: true,
  })
  tenantId?: TenantWhereUniqueInput | null;
}

export { SalaryItemCreateInput as SalaryItemCreateInput };
