/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SalaryItem } from "./SalaryItem";
import { SalaryItemCountArgs } from "./SalaryItemCountArgs";
import { SalaryItemFindManyArgs } from "./SalaryItemFindManyArgs";
import { SalaryItemFindUniqueArgs } from "./SalaryItemFindUniqueArgs";
import { CreateSalaryItemArgs } from "./CreateSalaryItemArgs";
import { UpdateSalaryItemArgs } from "./UpdateSalaryItemArgs";
import { DeleteSalaryItemArgs } from "./DeleteSalaryItemArgs";
import { SalaryItemGroup } from "../../salaryItemGroup/base/SalaryItemGroup";
import { SalaryItemType } from "../../salaryItemType/base/SalaryItemType";
import { SalaryLaw } from "../../salaryLaw/base/SalaryLaw";
import { Tenant } from "../../tenant/base/Tenant";
import { SalaryItemService } from "../salaryItem.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SalaryItem)
export class SalaryItemResolverBase {
  constructor(
    protected readonly service: SalaryItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "read",
    possession: "any",
  })
  async _salaryItemsMeta(
    @graphql.Args() args: SalaryItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SalaryItem])
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "read",
    possession: "any",
  })
  async salaryItems(
    @graphql.Args() args: SalaryItemFindManyArgs
  ): Promise<SalaryItem[]> {
    return this.service.salaryItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SalaryItem, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "read",
    possession: "own",
  })
  async salaryItem(
    @graphql.Args() args: SalaryItemFindUniqueArgs
  ): Promise<SalaryItem | null> {
    const result = await this.service.salaryItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SalaryItem)
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "create",
    possession: "any",
  })
  async createSalaryItem(
    @graphql.Args() args: CreateSalaryItemArgs
  ): Promise<SalaryItem> {
    return await this.service.createSalaryItem({
      ...args,
      data: {
        ...args.data,

        salaryItemGroupId: args.data.salaryItemGroupId
          ? {
              connect: args.data.salaryItemGroupId,
            }
          : undefined,

        salaryItemTypeId: {
          connect: args.data.salaryItemTypeId,
        },

        salaryLawId: args.data.salaryLawId
          ? {
              connect: args.data.salaryLawId,
            }
          : undefined,

        tenantId: args.data.tenantId
          ? {
              connect: args.data.tenantId,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SalaryItem)
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "update",
    possession: "any",
  })
  async updateSalaryItem(
    @graphql.Args() args: UpdateSalaryItemArgs
  ): Promise<SalaryItem | null> {
    try {
      return await this.service.updateSalaryItem({
        ...args,
        data: {
          ...args.data,

          salaryItemGroupId: args.data.salaryItemGroupId
            ? {
                connect: args.data.salaryItemGroupId,
              }
            : undefined,

          salaryItemTypeId: {
            connect: args.data.salaryItemTypeId,
          },

          salaryLawId: args.data.salaryLawId
            ? {
                connect: args.data.salaryLawId,
              }
            : undefined,

          tenantId: args.data.tenantId
            ? {
                connect: args.data.tenantId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SalaryItem)
  @nestAccessControl.UseRoles({
    resource: "SalaryItem",
    action: "delete",
    possession: "any",
  })
  async deleteSalaryItem(
    @graphql.Args() args: DeleteSalaryItemArgs
  ): Promise<SalaryItem | null> {
    try {
      return await this.service.deleteSalaryItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SalaryItemGroup, {
    nullable: true,
    name: "salaryItemGroupId",
  })
  @nestAccessControl.UseRoles({
    resource: "SalaryItemGroup",
    action: "read",
    possession: "any",
  })
  async getSalaryItemGroupId(
    @graphql.Parent() parent: SalaryItem
  ): Promise<SalaryItemGroup | null> {
    const result = await this.service.getSalaryItemGroupId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SalaryItemType, {
    nullable: true,
    name: "salaryItemTypeId",
  })
  @nestAccessControl.UseRoles({
    resource: "SalaryItemType",
    action: "read",
    possession: "any",
  })
  async getSalaryItemTypeId(
    @graphql.Parent() parent: SalaryItem
  ): Promise<SalaryItemType | null> {
    const result = await this.service.getSalaryItemTypeId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SalaryLaw, {
    nullable: true,
    name: "salaryLawId",
  })
  @nestAccessControl.UseRoles({
    resource: "SalaryLaw",
    action: "read",
    possession: "any",
  })
  async getSalaryLawId(
    @graphql.Parent() parent: SalaryItem
  ): Promise<SalaryLaw | null> {
    const result = await this.service.getSalaryLawId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Tenant, {
    nullable: true,
    name: "tenantId",
  })
  @nestAccessControl.UseRoles({
    resource: "Tenant",
    action: "read",
    possession: "any",
  })
  async getTenantId(
    @graphql.Parent() parent: SalaryItem
  ): Promise<Tenant | null> {
    const result = await this.service.getTenantId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
