import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringFilter } from "../../util/StringFilter";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { SaleDetailListRelationFilter } from "../saleDetail/SaleDetailListRelationFilter";
import { SalePriceTypeWhereUniqueInput } from "../salePriceType/SalePriceTypeWhereUniqueInput";
import { SaleReturnListRelationFilter } from "../saleReturn/SaleReturnListRelationFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type SaleWhereInput = {
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  customerId?: CustomerWhereUniqueInput;
  discountTotal?: DecimalFilter;
  id?: StringFilter;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput;
  isActive?: BooleanFilter;
  isCancelled?: BooleanFilter;
  isReplicated?: BooleanFilter;
  netTotal?: DecimalNullableFilter;
  nonTaxableTotal?: DecimalNullableFilter;
  note?: StringNullableFilter;
  paid?: DecimalNullableFilter;
  paymentTypeId?: PaymentTypeWhereUniqueInput;
  referenceNumber?: StringNullableFilter;
  remaining?: DecimalNullableFilter;
  saleDate?: DateTimeFilter;
  saleDetails?: SaleDetailListRelationFilter;
  salePriceTypeId?: SalePriceTypeWhereUniqueInput;
  saleReturns?: SaleReturnListRelationFilter;
  saleTotal?: DecimalFilter;
  sequenceNumber?: StringFilter;
  storeId?: StoreWhereUniqueInput;
  tax?: DecimalNullableFilter;
  taxRate?: DecimalNullableFilter;
  taxableTotal?: DecimalNullableFilter;
  tenantId?: TenantWhereUniqueInput;
};
