import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { Decimal } from "decimal.js";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { SaleDetailCreateNestedManyWithoutSalesInput } from "./SaleDetailCreateNestedManyWithoutSalesInput";
import { SalePriceTypeWhereUniqueInput } from "../salePriceType/SalePriceTypeWhereUniqueInput";
import { SaleReturnCreateNestedManyWithoutSalesInput } from "./SaleReturnCreateNestedManyWithoutSalesInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type SaleCreateInput = {
  cashRepositoryId: CashRepositoryWhereUniqueInput;
  customerId: CustomerWhereUniqueInput;
  discountTotal: Decimal;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput | null;
  isActive: boolean;
  isCancelled: boolean;
  isReplicated: boolean;
  netTotal?: Decimal | null;
  nonTaxableTotal?: Decimal | null;
  note?: string | null;
  paid?: Decimal | null;
  paymentTypeId: PaymentTypeWhereUniqueInput;
  referenceNumber?: string | null;
  remaining?: Decimal | null;
  saleDate: Date;
  saleDetails?: SaleDetailCreateNestedManyWithoutSalesInput;
  salePriceTypeId: SalePriceTypeWhereUniqueInput;
  saleReturns?: SaleReturnCreateNestedManyWithoutSalesInput;
  saleTotal: Decimal;
  sequenceNumber: string;
  storeId: StoreWhereUniqueInput;
  tax?: Decimal | null;
  taxRate?: Decimal | null;
  taxableTotal?: Decimal | null;
  tenantId?: TenantWhereUniqueInput | null;
};
