import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringFilter } from "../../util/StringFilter";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PaymentTermWhereUniqueInput } from "../paymentTerm/PaymentTermWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { SaleWhereUniqueInput } from "../sale/SaleWhereUniqueInput";
import { SalePriceTypeWhereUniqueInput } from "../salePriceType/SalePriceTypeWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { SaleReturnDetailListRelationFilter } from "../saleReturnDetail/SaleReturnDetailListRelationFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type SaleReturnWhereInput = {
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  customerId?: CustomerWhereUniqueInput;
  discountTotal?: DecimalFilter;
  id?: StringFilter;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput;
  isActive?: BooleanFilter;
  isCancelled?: BooleanFilter;
  isReplicated?: BooleanFilter;
  netTotal?: DecimalFilter;
  nonTaxableTotal?: DecimalNullableFilter;
  note?: StringNullableFilter;
  paid?: DecimalFilter;
  paymentTermId?: PaymentTermWhereUniqueInput;
  paymentTypeId?: PaymentTypeWhereUniqueInput;
  referenceNumber?: StringNullableFilter;
  remaining?: DecimalFilter;
  returnTotal?: DecimalFilter;
  saleId?: SaleWhereUniqueInput;
  salePriceTyped?: SalePriceTypeWhereUniqueInput;
  saleReturnDate?: DateTimeFilter;
  saleReturnDetails?: SaleReturnDetailListRelationFilter;
  sequence?: StringFilter;
  storeId?: StoreWhereUniqueInput;
  tax?: DecimalNullableFilter;
  taxRate?: DecimalNullableFilter;
  taxableTotal?: DecimalNullableFilter;
  tenant?: TenantWhereUniqueInput;
};
