import { ControlTypeWhereUniqueInput } from "../controlType/ControlTypeWhereUniqueInput";
import { CustomerElevatorCreateNestedManyWithoutElevatorsInput } from "./CustomerElevatorCreateNestedManyWithoutElevatorsInput";
import { CustomerUserCreateNestedManyWithoutElevatorsInput } from "./CustomerUserCreateNestedManyWithoutElevatorsInput";
import { Decimal } from "decimal.js";
import { DoorTypeWhereUniqueInput } from "../doorType/DoorTypeWhereUniqueInput";
import { ElevatorSparePartCreateNestedManyWithoutElevatorsInput } from "./ElevatorSparePartCreateNestedManyWithoutElevatorsInput";
import { ElevatorTypeWhereUniqueInput } from "../elevatorType/ElevatorTypeWhereUniqueInput";
import { FailureReportingCreateNestedManyWithoutElevatorsInput } from "./FailureReportingCreateNestedManyWithoutElevatorsInput";
import { InstallationContractCreateNestedManyWithoutElevatorsInput } from "./InstallationContractCreateNestedManyWithoutElevatorsInput";
import { MaintenanceContractCreateNestedManyWithoutElevatorsInput } from "./MaintenanceContractCreateNestedManyWithoutElevatorsInput";
import { MaintenanceVisitCreateNestedManyWithoutElevatorsInput } from "./MaintenanceVisitCreateNestedManyWithoutElevatorsInput";
import { MotorTypeWhereUniqueInput } from "../motorType/MotorTypeWhereUniqueInput";
import { PeriodicMaintenanceOrderCreateNestedManyWithoutElevatorsInput } from "./PeriodicMaintenanceOrderCreateNestedManyWithoutElevatorsInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";

export type ElevatorCreateInput = {
  bannerSize?: string | null;
  cabinetSize?: string | null;
  code?: string | null;
  controlTypeId?: ControlTypeWhereUniqueInput | null;
  customerElevators?: CustomerElevatorCreateNestedManyWithoutElevatorsInput;
  customerUsers?: CustomerUserCreateNestedManyWithoutElevatorsInput;
  description?: string | null;
  doorSize?: Decimal | null;
  doorTypeId?: DoorTypeWhereUniqueInput | null;
  elevatorSpareParts?: ElevatorSparePartCreateNestedManyWithoutElevatorsInput;
  elevatorTypeId?: ElevatorTypeWhereUniqueInput | null;
  failureReportings?: FailureReportingCreateNestedManyWithoutElevatorsInput;
  freight?: Decimal | null;
  installationContracts?: InstallationContractCreateNestedManyWithoutElevatorsInput;
  maintenanceContracts?: MaintenanceContractCreateNestedManyWithoutElevatorsInput;
  maintenanceVisits?: MaintenanceVisitCreateNestedManyWithoutElevatorsInput;
  motorPower?: string | null;
  motorTypeId?: MotorTypeWhereUniqueInput | null;
  name: string;
  normalizedName: string;
  periodicMaintenanceOrders?: PeriodicMaintenanceOrderCreateNestedManyWithoutElevatorsInput;
  personsCount?: number | null;
  stationsCount?: number | null;
  storeId: StoreWhereUniqueInput;
};
