import { ControlType } from "../controlType/ControlType";
import { CustomerElevator } from "../customerElevator/CustomerElevator";
import { CustomerUser } from "../customerUser/CustomerUser";
import { Decimal } from "decimal.js";
import { DoorType } from "../doorType/DoorType";
import { ElevatorSparePart } from "../elevatorSparePart/ElevatorSparePart";
import { ElevatorType } from "../elevatorType/ElevatorType";
import { FailureReporting } from "../failureReporting/FailureReporting";
import { InstallationContract } from "../installationContract/InstallationContract";
import { MaintenanceContract } from "../maintenanceContract/MaintenanceContract";
import { MaintenanceVisit } from "../maintenanceVisit/MaintenanceVisit";
import { MotorType } from "../motorType/MotorType";
import { PeriodicMaintenanceOrder } from "../periodicMaintenanceOrder/PeriodicMaintenanceOrder";
import { Store } from "../store/Store";

export type Elevator = {
  bannerSize: string | null;
  cabinetSize: string | null;
  code: string | null;
  controlTypeId?: ControlType | null;
  createdAt: Date;
  customerElevators?: Array<CustomerElevator>;
  customerUsers?: Array<CustomerUser>;
  description: string | null;
  doorSize: Decimal | null;
  doorTypeId?: DoorType | null;
  elevatorSpareParts?: Array<ElevatorSparePart>;
  elevatorTypeId?: ElevatorType | null;
  failureReportings?: Array<FailureReporting>;
  freight: Decimal | null;
  id: string;
  installationContracts?: Array<InstallationContract>;
  maintenanceContracts?: Array<MaintenanceContract>;
  maintenanceVisits?: Array<MaintenanceVisit>;
  motorPower: string | null;
  motorTypeId?: MotorType | null;
  name: string;
  normalizedName: string;
  periodicMaintenanceOrders?: Array<PeriodicMaintenanceOrder>;
  personsCount: number | null;
  stationsCount: number | null;
  storeId?: Store;
  updatedAt: Date;
};
