import { ControlTypeWhereUniqueInput } from "../controlType/ControlTypeWhereUniqueInput";
import { CustomerElevatorUpdateManyWithoutElevatorsInput } from "./CustomerElevatorUpdateManyWithoutElevatorsInput";
import { CustomerUserUpdateManyWithoutElevatorsInput } from "./CustomerUserUpdateManyWithoutElevatorsInput";
import { Decimal } from "decimal.js";
import { DoorTypeWhereUniqueInput } from "../doorType/DoorTypeWhereUniqueInput";
import { ElevatorSparePartUpdateManyWithoutElevatorsInput } from "./ElevatorSparePartUpdateManyWithoutElevatorsInput";
import { ElevatorTypeWhereUniqueInput } from "../elevatorType/ElevatorTypeWhereUniqueInput";
import { FailureReportingUpdateManyWithoutElevatorsInput } from "./FailureReportingUpdateManyWithoutElevatorsInput";
import { InstallationContractUpdateManyWithoutElevatorsInput } from "./InstallationContractUpdateManyWithoutElevatorsInput";
import { MaintenanceContractUpdateManyWithoutElevatorsInput } from "./MaintenanceContractUpdateManyWithoutElevatorsInput";
import { MaintenanceVisitUpdateManyWithoutElevatorsInput } from "./MaintenanceVisitUpdateManyWithoutElevatorsInput";
import { MotorTypeWhereUniqueInput } from "../motorType/MotorTypeWhereUniqueInput";
import { PeriodicMaintenanceOrderUpdateManyWithoutElevatorsInput } from "./PeriodicMaintenanceOrderUpdateManyWithoutElevatorsInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";

export type ElevatorUpdateInput = {
  bannerSize?: string | null;
  cabinetSize?: string | null;
  code?: string | null;
  controlTypeId?: ControlTypeWhereUniqueInput | null;
  customerElevators?: CustomerElevatorUpdateManyWithoutElevatorsInput;
  customerUsers?: CustomerUserUpdateManyWithoutElevatorsInput;
  description?: string | null;
  doorSize?: Decimal | null;
  doorTypeId?: DoorTypeWhereUniqueInput | null;
  elevatorSpareParts?: ElevatorSparePartUpdateManyWithoutElevatorsInput;
  elevatorTypeId?: ElevatorTypeWhereUniqueInput | null;
  failureReportings?: FailureReportingUpdateManyWithoutElevatorsInput;
  freight?: Decimal | null;
  installationContracts?: InstallationContractUpdateManyWithoutElevatorsInput;
  maintenanceContracts?: MaintenanceContractUpdateManyWithoutElevatorsInput;
  maintenanceVisits?: MaintenanceVisitUpdateManyWithoutElevatorsInput;
  motorPower?: string | null;
  motorTypeId?: MotorTypeWhereUniqueInput | null;
  name?: string;
  normalizedName?: string;
  periodicMaintenanceOrders?: PeriodicMaintenanceOrderUpdateManyWithoutElevatorsInput;
  personsCount?: number | null;
  stationsCount?: number | null;
  storeId?: StoreWhereUniqueInput;
};
