import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ControlTypeWhereUniqueInput } from "../controlType/ControlTypeWhereUniqueInput";
import { CustomerElevatorListRelationFilter } from "../customerElevator/CustomerElevatorListRelationFilter";
import { CustomerUserListRelationFilter } from "../customerUser/CustomerUserListRelationFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { DoorTypeWhereUniqueInput } from "../doorType/DoorTypeWhereUniqueInput";
import { ElevatorSparePartListRelationFilter } from "../elevatorSparePart/ElevatorSparePartListRelationFilter";
import { ElevatorTypeWhereUniqueInput } from "../elevatorType/ElevatorTypeWhereUniqueInput";
import { FailureReportingListRelationFilter } from "../failureReporting/FailureReportingListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { InstallationContractListRelationFilter } from "../installationContract/InstallationContractListRelationFilter";
import { MaintenanceContractListRelationFilter } from "../maintenanceContract/MaintenanceContractListRelationFilter";
import { MaintenanceVisitListRelationFilter } from "../maintenanceVisit/MaintenanceVisitListRelationFilter";
import { MotorTypeWhereUniqueInput } from "../motorType/MotorTypeWhereUniqueInput";
import { PeriodicMaintenanceOrderListRelationFilter } from "../periodicMaintenanceOrder/PeriodicMaintenanceOrderListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";

export type ElevatorWhereInput = {
  bannerSize?: StringNullableFilter;
  cabinetSize?: StringNullableFilter;
  code?: StringNullableFilter;
  controlTypeId?: ControlTypeWhereUniqueInput;
  customerElevators?: CustomerElevatorListRelationFilter;
  customerUsers?: CustomerUserListRelationFilter;
  description?: StringNullableFilter;
  doorSize?: DecimalNullableFilter;
  doorTypeId?: DoorTypeWhereUniqueInput;
  elevatorSpareParts?: ElevatorSparePartListRelationFilter;
  elevatorTypeId?: ElevatorTypeWhereUniqueInput;
  failureReportings?: FailureReportingListRelationFilter;
  freight?: DecimalNullableFilter;
  id?: StringFilter;
  installationContracts?: InstallationContractListRelationFilter;
  maintenanceContracts?: MaintenanceContractListRelationFilter;
  maintenanceVisits?: MaintenanceVisitListRelationFilter;
  motorPower?: StringNullableFilter;
  motorTypeId?: MotorTypeWhereUniqueInput;
  name?: StringFilter;
  normalizedName?: StringFilter;
  periodicMaintenanceOrders?: PeriodicMaintenanceOrderListRelationFilter;
  personsCount?: IntNullableFilter;
  stationsCount?: IntNullableFilter;
  storeId?: StoreWhereUniqueInput;
};
