import { AttendanceCreateNestedManyWithoutEmployeesInput } from "./AttendanceCreateNestedManyWithoutEmployeesInput";
import { Decimal } from "decimal.js";
import { BonusRequestCreateNestedManyWithoutEmployeesInput } from "./BonusRequestCreateNestedManyWithoutEmployeesInput";
import { CheckInOutCreateNestedManyWithoutEmployeesInput } from "./CheckInOutCreateNestedManyWithoutEmployeesInput";
import { DailyMovementRequestCreateNestedManyWithoutEmployeesInput } from "./DailyMovementRequestCreateNestedManyWithoutEmployeesInput";
import { DayOffRequestCreateNestedManyWithoutEmployeesInput } from "./DayOffRequestCreateNestedManyWithoutEmployeesInput";
import { EmployeeDepartmentWhereUniqueInput } from "../employeeDepartment/EmployeeDepartmentWhereUniqueInput";
import { EmployeeGroupWhereUniqueInput } from "../employeeGroup/EmployeeGroupWhereUniqueInput";
import { EmployeeRoleWhereUniqueInput } from "../employeeRole/EmployeeRoleWhereUniqueInput";
import { JobTitleWhereUniqueInput } from "../jobTitle/JobTitleWhereUniqueInput";
import { LeaveRequestCreateNestedManyWithoutEmployeesInput } from "./LeaveRequestCreateNestedManyWithoutEmployeesInput";
import { OverNightRequestCreateNestedManyWithoutEmployeesInput } from "./OverNightRequestCreateNestedManyWithoutEmployeesInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type EmployeeCreateInput = {
  attendances?: AttendanceCreateNestedManyWithoutEmployeesInput;
  balance?: Decimal | null;
  bonusRequests?: BonusRequestCreateNestedManyWithoutEmployeesInput;
  checkInOuts?: CheckInOutCreateNestedManyWithoutEmployeesInput;
  code?: string | null;
  dailyMovementRequests?: DailyMovementRequestCreateNestedManyWithoutEmployeesInput;
  dayOffRequests?: DayOffRequestCreateNestedManyWithoutEmployeesInput;
  employeeDepartmentId?: EmployeeDepartmentWhereUniqueInput | null;
  employeeGroup?: EmployeeGroupWhereUniqueInput | null;
  employeeRoleId?: EmployeeRoleWhereUniqueInput | null;
  hireDate?: Date | null;
  isActive: boolean;
  jobTitle?: JobTitleWhereUniqueInput | null;
  lastYearBalance?: Decimal | null;
  leavingPermissionRequests?: LeaveRequestCreateNestedManyWithoutEmployeesInput;
  name: string;
  note?: string | null;
  overNightRequests?: OverNightRequestCreateNestedManyWithoutEmployeesInput;
  remainingBalance?: Decimal | null;
  tenantId?: TenantWhereUniqueInput | null;
  usedBalance?: Decimal | null;
};
