import { Decimal } from "decimal.js";
import { Tenant } from "../tenant/Tenant";
import { WorkCenterAlternative } from "../workCenterAlternative/WorkCenterAlternative";
import { WorkCenterCapacity } from "../workCenterCapacity/WorkCenterCapacity";
import { WorkCenterProductivity } from "../workCenterProductivity/WorkCenterProductivity";
import { WorkCenterProductivityLoss } from "../workCenterProductivityLoss/WorkCenterProductivityLoss";
import { WorkCenterRouting } from "../workCenterRouting/WorkCenterRouting";
import { WorkCenterWorkCenterTag } from "../workCenterWorkCenterTag/WorkCenterWorkCenterTag";

export type WorkCenter = {
  analyticDistribution: string | null;
  code: string | null;
  color: number | null;
  costPerHour: Decimal | null;
  createdAt: Date;
  defaultCapacity: Decimal | null;
  id: string;
  isActive: boolean;
  isProductive: boolean;
  name: string;
  normalizedName: string;
  note: string | null;
  oeeTareget: Decimal | null;
  sequence: number;
  startTime: Decimal | null;
  stopTime: Decimal | null;
  tenantId?: Tenant | null;
  timeEfficiency: Decimal | null;
  updatedAt: Date;
  workCenterAlternativeWorkCenters?: Array<WorkCenterAlternative>;
  workCenterAlternatives?: Array<WorkCenterAlternative>;
  workCenterCapacities?: Array<WorkCenterCapacity>;
  workCenterProductivities?: Array<WorkCenterProductivity>;
  workCenterProductivityLosses?: Array<WorkCenterProductivityLoss>;
  workCenterRoutings?: Array<WorkCenterRouting>;
  workCenterWorkCenterTags?: Array<WorkCenterWorkCenterTag>;
};
