import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { Decimal } from "decimal.js";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { OrderStatusWhereUniqueInput } from "../orderStatus/OrderStatusWhereUniqueInput";
import { PaymentStatusWhereUniqueInput } from "../paymentStatus/PaymentStatusWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { SaleOrderDetailUpdateManyWithoutSaleOrdersInput } from "./SaleOrderDetailUpdateManyWithoutSaleOrdersInput";
import { SalePriceTypeWhereUniqueInput } from "../salePriceType/SalePriceTypeWhereUniqueInput";
import { SaleQuotationWhereUniqueInput } from "../saleQuotation/SaleQuotationWhereUniqueInput";
import { ShippingStatusWhereUniqueInput } from "../shippingStatus/ShippingStatusWhereUniqueInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type SaleOrderUpdateInput = {
  billingAddress?: string | null;
  cashRepositoryId?: CashRepositoryWhereUniqueInput | null;
  customerId?: CustomerWhereUniqueInput;
  deliveryDate?: Date | null;
  discountTotal?: Decimal;
  expectedDeliveryDate?: Date | null;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput | null;
  isActive?: boolean;
  isCancelled?: boolean;
  isReplicated?: boolean;
  netTotal?: Decimal;
  nonTaxableTotal?: Decimal | null;
  note?: string | null;
  orderStatus?: OrderStatusWhereUniqueInput;
  paymentStatus?: PaymentStatusWhereUniqueInput | null;
  paymentTypeId?: PaymentTypeWhereUniqueInput | null;
  referenceNumber?: string | null;
  saleOrderDate?: Date;
  saleOrderDetails?: SaleOrderDetailUpdateManyWithoutSaleOrdersInput;
  salePriceType?: SalePriceTypeWhereUniqueInput;
  salePriceTypeId?: number;
  saleQuotation?: SaleQuotationWhereUniqueInput | null;
  saleTotal?: Decimal;
  shippingAddress?: string | null;
  shippingCost?: Decimal | null;
  shippingStatus?: ShippingStatusWhereUniqueInput | null;
  storeId?: StoreWhereUniqueInput | null;
  tax?: Decimal | null;
  taxRate?: Decimal | null;
  taxableTotal?: Decimal | null;
  tenant?: TenantWhereUniqueInput | null;
  transactionDateTime?: Date | null;
};
