import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringFilter } from "../../util/StringFilter";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { OrderStatusWhereUniqueInput } from "../orderStatus/OrderStatusWhereUniqueInput";
import { PaymentStatusWhereUniqueInput } from "../paymentStatus/PaymentStatusWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { SaleOrderDetailListRelationFilter } from "../saleOrderDetail/SaleOrderDetailListRelationFilter";
import { SalePriceTypeWhereUniqueInput } from "../salePriceType/SalePriceTypeWhereUniqueInput";
import { FloatFilter } from "../../util/FloatFilter";
import { SaleQuotationWhereUniqueInput } from "../saleQuotation/SaleQuotationWhereUniqueInput";
import { ShippingStatusWhereUniqueInput } from "../shippingStatus/ShippingStatusWhereUniqueInput";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type SaleOrderWhereInput = {
  billingAddress?: StringNullableFilter;
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  customerId?: CustomerWhereUniqueInput;
  deliveryDate?: DateTimeNullableFilter;
  discountTotal?: DecimalFilter;
  expectedDeliveryDate?: DateTimeNullableFilter;
  id?: StringFilter;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput;
  isActive?: BooleanFilter;
  isCancelled?: BooleanFilter;
  isReplicated?: BooleanFilter;
  netTotal?: DecimalFilter;
  nonTaxableTotal?: DecimalNullableFilter;
  note?: StringNullableFilter;
  orderStatus?: OrderStatusWhereUniqueInput;
  paymentStatus?: PaymentStatusWhereUniqueInput;
  paymentTypeId?: PaymentTypeWhereUniqueInput;
  referenceNumber?: StringNullableFilter;
  saleOrderDate?: DateTimeFilter;
  saleOrderDetails?: SaleOrderDetailListRelationFilter;
  salePriceType?: SalePriceTypeWhereUniqueInput;
  salePriceTypeId?: FloatFilter;
  saleQuotation?: SaleQuotationWhereUniqueInput;
  saleTotal?: DecimalFilter;
  shippingAddress?: StringNullableFilter;
  shippingCost?: DecimalNullableFilter;
  shippingStatus?: ShippingStatusWhereUniqueInput;
  storeId?: StoreWhereUniqueInput;
  tax?: DecimalNullableFilter;
  taxRate?: DecimalNullableFilter;
  taxableTotal?: DecimalNullableFilter;
  tenant?: TenantWhereUniqueInput;
  transactionDateTime?: DateTimeNullableFilter;
};
