import { CashRepository } from "../cashRepository/CashRepository";
import { Customer } from "../customer/Customer";
import { Decimal } from "decimal.js";
import { InvoiceType } from "../invoiceType/InvoiceType";
import { OrderStatus } from "../orderStatus/OrderStatus";
import { PaymentStatus } from "../paymentStatus/PaymentStatus";
import { PaymentType } from "../paymentType/PaymentType";
import { SaleOrderDetail } from "../saleOrderDetail/SaleOrderDetail";
import { SalePriceType } from "../salePriceType/SalePriceType";
import { SaleQuotation } from "../saleQuotation/SaleQuotation";
import { ShippingStatus } from "../shippingStatus/ShippingStatus";
import { Store } from "../store/Store";
import { Tenant } from "../tenant/Tenant";

export type SaleOrder = {
  billingAddress: string | null;
  cashRepositoryId?: CashRepository | null;
  createdAt: Date;
  customerId?: Customer;
  deliveryDate: Date | null;
  discountTotal: Decimal;
  expectedDeliveryDate: Date | null;
  id: string;
  invoiceTypeId?: InvoiceType | null;
  isActive: boolean;
  isCancelled: boolean;
  isReplicated: boolean;
  netTotal: Decimal;
  nonTaxableTotal: Decimal | null;
  note: string | null;
  orderStatus?: OrderStatus;
  paymentStatus?: PaymentStatus | null;
  paymentTypeId?: PaymentType | null;
  referenceNumber: string | null;
  saleOrderDate: Date;
  saleOrderDetails?: Array<SaleOrderDetail>;
  salePriceType?: SalePriceType;
  salePriceTypeId: number;
  saleQuotation?: SaleQuotation | null;
  saleTotal: Decimal;
  shippingAddress: string | null;
  shippingCost: Decimal | null;
  shippingStatus?: ShippingStatus | null;
  storeId?: Store | null;
  tax: Decimal | null;
  taxRate: Decimal | null;
  taxableTotal: Decimal | null;
  tenant?: Tenant | null;
  transactionDateTime: Date | null;
  updatedAt: Date;
};
