import { SortOrder } from "../../util/SortOrder";

export type CustomerOrderByInput = {
  DefaultSalePriceTypeId?: SortOrder;
  address?: SortOrder;
  code?: SortOrder;
  createdAt?: SortOrder;
  credit?: SortOrder;
  currencyId?: SortOrder;
  debit?: SortOrder;
  description?: SortOrder;
  email?: SortOrder;
  firstBalance?: SortOrder;
  firstBalanceDate?: SortOrder;
  id?: SortOrder;
  isActive?: SortOrder;
  isSystem?: SortOrder;
  isUnderRevision?: SortOrder;
  maxAllowedDebit?: SortOrder;
  name?: SortOrder;
  normalizedName?: SortOrder;
  phoneNumber?: SortOrder;
  previousBalance?: SortOrder;
  revisionDate?: SortOrder;
  saleDiscountRate?: SortOrder;
  supplierId?: SortOrder;
  taxNumber?: SortOrder;
  updatedAt?: SortOrder;
  website?: SortOrder;
};
