import { Decimal } from "decimal.js";
import { CurrencyWhereUniqueInput } from "../currency/CurrencyWhereUniqueInput";
import { ProductionOrderUpdateManyWithoutCustomersInput } from "./ProductionOrderUpdateManyWithoutCustomersInput";

export type CustomerUpdateInput = {
  DefaultSalePriceTypeId?: number | null;
  address?: string | null;
  code?: string | null;
  credit?: Decimal | null;
  currency?: CurrencyWhereUniqueInput | null;
  debit?: Decimal | null;
  description?: string | null;
  email?: string | null;
  firstBalance?: Decimal | null;
  firstBalanceDate?: Date | null;
  isActive?: boolean | null;
  isSystem?: boolean | null;
  isUnderRevision?: boolean | null;
  maxAllowedDebit?: Decimal | null;
  name?: string;
  normalizedName?: string;
  phoneNumber?: string | null;
  previousBalance?: Decimal | null;
  productionOrders?: ProductionOrderUpdateManyWithoutCustomersInput;
  revisionDate?: Date | null;
  saleDiscountRate?: Decimal | null;
  supplierId?: string | null;
  taxNumber?: string | null;
  website?: string | null;
};
