import { Decimal } from "decimal.js";
import { Currency } from "../currency/Currency";
import { ProductionOrder } from "../productionOrder/ProductionOrder";

export type Customer = {
  DefaultSalePriceTypeId: number | null;
  address: string | null;
  code: string | null;
  createdAt: Date;
  credit: Decimal | null;
  currency?: Currency | null;
  debit: Decimal | null;
  description: string | null;
  email: string | null;
  firstBalance: Decimal | null;
  firstBalanceDate: Date | null;
  id: string;
  isActive: boolean | null;
  isSystem: boolean | null;
  isUnderRevision: boolean | null;
  maxAllowedDebit: Decimal | null;
  name: string;
  normalizedName: string;
  phoneNumber: string | null;
  previousBalance: Decimal | null;
  productionOrders?: Array<ProductionOrder>;
  revisionDate: Date | null;
  saleDiscountRate: Decimal | null;
  supplierId: string | null;
  taxNumber: string | null;
  updatedAt: Date;
  website: string | null;
};
