import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { CurrencyWhereUniqueInput } from "../currency/CurrencyWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ProductionOrderListRelationFilter } from "../productionOrder/ProductionOrderListRelationFilter";
import { SaleReturnListRelationFilter } from "../saleReturn/SaleReturnListRelationFilter";
import { SaleListRelationFilter } from "../sale/SaleListRelationFilter";
import { SupplierListRelationFilter } from "../supplier/SupplierListRelationFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type CustomerWhereInput = {
  DefaultSalePriceTypeId?: FloatNullableFilter;
  address?: StringNullableFilter;
  code?: StringNullableFilter;
  credit?: DecimalNullableFilter;
  currencyId?: CurrencyWhereUniqueInput;
  debit?: DecimalNullableFilter;
  description?: StringNullableFilter;
  email?: StringNullableFilter;
  firstBalance?: DecimalNullableFilter;
  firstBalanceDate?: DateTimeNullableFilter;
  id?: StringFilter;
  isActive?: BooleanFilter;
  isSystem?: BooleanNullableFilter;
  isUnderRevision?: BooleanNullableFilter;
  maxAllowedDebit?: DecimalNullableFilter;
  name?: StringFilter;
  normalizedName?: StringFilter;
  phoneNumber?: StringNullableFilter;
  previousBalance?: DecimalNullableFilter;
  productionOrders?: ProductionOrderListRelationFilter;
  revisionDate?: DateTimeNullableFilter;
  saleDiscountRate?: DecimalNullableFilter;
  saleReturns?: SaleReturnListRelationFilter;
  sales?: SaleListRelationFilter;
  supplierId?: StringNullableFilter;
  suppliers?: SupplierListRelationFilter;
  taxNumber?: StringNullableFilter;
  tenant?: TenantWhereUniqueInput;
  website?: StringNullableFilter;
};
