import { Decimal } from "decimal.js";
import { Currency } from "../currency/Currency";
import { ProductionOrder } from "../productionOrder/ProductionOrder";
import { SaleReturn } from "../saleReturn/SaleReturn";
import { Sale } from "../sale/Sale";
import { Supplier } from "../supplier/Supplier";
import { Tenant } from "../tenant/Tenant";

export type Customer = {
  DefaultSalePriceTypeId: number | null;
  address: string | null;
  code: string | null;
  createdAt: Date;
  credit: Decimal | null;
  currencyId?: Currency | null;
  debit: Decimal | null;
  description: string | null;
  email: string | null;
  firstBalance: Decimal | null;
  firstBalanceDate: Date | null;
  id: string;
  isActive: boolean;
  isSystem: boolean | null;
  isUnderRevision: boolean | null;
  maxAllowedDebit: Decimal | null;
  name: string;
  normalizedName: string;
  phoneNumber: string | null;
  previousBalance: Decimal | null;
  productionOrders?: Array<ProductionOrder>;
  revisionDate: Date | null;
  saleDiscountRate: Decimal | null;
  saleReturns?: Array<SaleReturn>;
  sales?: Array<Sale>;
  supplierId: string | null;
  suppliers?: Array<Supplier>;
  taxNumber: string | null;
  tenant?: Tenant | null;
  updatedAt: Date;
  website: string | null;
};
