import { CashRepositoryWhereUniqueInput } from "../cashRepository/CashRepositoryWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringFilter } from "../../util/StringFilter";
import { InvoiceTypeWhereUniqueInput } from "../invoiceType/InvoiceTypeWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PaymentTermWhereUniqueInput } from "../paymentTerm/PaymentTermWhereUniqueInput";
import { PaymentTypeWhereUniqueInput } from "../paymentType/PaymentTypeWhereUniqueInput";
import { PurchaseWhereUniqueInput } from "../purchase/PurchaseWhereUniqueInput";
import { PurchasePriceTypeWhereUniqueInput } from "../purchasePriceType/PurchasePriceTypeWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { PurchaseReturnDetailListRelationFilter } from "../purchaseReturnDetail/PurchaseReturnDetailListRelationFilter";
import { StoreWhereUniqueInput } from "../store/StoreWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";

export type PurchaseReturnWhereInput = {
  cashRepositoryId?: CashRepositoryWhereUniqueInput;
  discountTotal?: DecimalFilter;
  id?: StringFilter;
  invoiceTypeId?: InvoiceTypeWhereUniqueInput;
  isActive?: BooleanFilter;
  isCancelled?: BooleanFilter;
  isReplicated?: BooleanFilter;
  netTotal?: DecimalFilter;
  nonTaxableTotal?: DecimalNullableFilter;
  note?: StringNullableFilter;
  paid?: DecimalFilter;
  paymentTermId?: PaymentTermWhereUniqueInput;
  paymentTypeId?: PaymentTypeWhereUniqueInput;
  purchaseId?: PurchaseWhereUniqueInput;
  purchasePriceTypeId?: PurchasePriceTypeWhereUniqueInput;
  purchaseReturnDate?: DateTimeFilter;
  purchaseReturnDetails?: PurchaseReturnDetailListRelationFilter;
  purchaseReturnTotal?: DecimalFilter;
  referenceNumber?: StringNullableFilter;
  remaining?: DecimalFilter;
  sequenceNumber?: StringFilter;
  storeId?: StoreWhereUniqueInput;
  supplierId?: SupplierWhereUniqueInput;
  tax?: DecimalNullableFilter;
  taxRate?: DecimalNullableFilter;
  taxableTotal?: DecimalNullableFilter;
  tenantId?: TenantWhereUniqueInput;
};
